// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const completeAuthorizationRequest = `-- name: CompleteAuthorizationRequest :execresult
UPDATE
    oauth_authorization_requests
SET
    completed_at = now()
WHERE
    id = $1
    AND completed_at IS NULL
    AND expires_at > now()
`

func (q *Queries) CompleteAuthorizationRequest(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, completeAuthorizationRequest, id)
}

const consumeLoginState = `-- name: ConsumeLoginState :one
UPDATE
    oauth_login_states
SET
    consumed_at = now()
WHERE
    state_hash = $1
    AND consumed_at IS NULL
    AND expires_at > now()
RETURNING
    connection_id,
    coalesce(authorization_request_id::text, '')::text AS authorization_request_id,
    purpose
`

type ConsumeLoginStateRow struct {
	ConnectionID           string
	AuthorizationRequestID string
	Purpose                string
}

func (q *Queries) ConsumeLoginState(ctx context.Context, stateHash string) (ConsumeLoginStateRow, error) {
	row := q.db.QueryRow(ctx, consumeLoginState, stateHash)
	var i ConsumeLoginStateRow
	err := row.Scan(&i.ConnectionID, &i.AuthorizationRequestID, &i.Purpose)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT
    count(*)
FROM
    users
WHERE
    deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :execresult
INSERT INTO oauth_authorization_codes (code_hash, authorization_request_id, user_id, client_id, redirect_uri,
    code_challenge, expires_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuthorizationCodeParams struct {
	CodeHash               string
	AuthorizationRequestID string
	UserID                 string
	ClientID               string
	RedirectUri            string
	CodeChallenge          string
	ExpiresAt              time.Time
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createAuthorizationCode,
		arg.CodeHash,
		arg.AuthorizationRequestID,
		arg.UserID,
		arg.ClientID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
}

const createAuthorizationRequest = `-- name: CreateAuthorizationRequest :one
INSERT INTO oauth_authorization_requests (client_id, redirect_uri, state, code_challenge, code_challenge_method, expires_at)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id
`

type CreateAuthorizationRequestParams struct {
	ClientID            string
	RedirectUri         string
	State               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           time.Time
}

func (q *Queries) CreateAuthorizationRequest(ctx context.Context, arg CreateAuthorizationRequestParams) (string, error) {
	row := q.db.QueryRow(ctx, createAuthorizationRequest,
		arg.ClientID,
		arg.RedirectUri,
		arg.State,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createBrowserSession = `-- name: CreateBrowserSession :execresult
INSERT INTO browser_sessions (token_hash, user_id, authentication_method, expires_at)
    VALUES ($1, $2, $3, $4)
`

type CreateBrowserSessionParams struct {
	TokenHash            string
	UserID               string
	AuthenticationMethod string
	ExpiresAt            time.Time
}

func (q *Queries) CreateBrowserSession(ctx context.Context, arg CreateBrowserSessionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createBrowserSession,
		arg.TokenHash,
		arg.UserID,
		arg.AuthenticationMethod,
		arg.ExpiresAt,
	)
}

const createIdentityUser = `-- name: CreateIdentityUser :one
INSERT INTO users (name, email, avatar_url, ROLE, last_login_at)
    VALUES ($1, $2, NULLIF ($3::text, ''),
	'user', now())
ON CONFLICT (lower(email))
WHERE
    deleted_at IS NULL
        DO UPDATE SET
            name = EXCLUDED.name,
            avatar_url = EXCLUDED.avatar_url,
            last_login_at = now(),
            updated_at = now()
        WHERE
            users.role = 'user'
            AND users.status = 'active'
        RETURNING
            id,
            name,
            email,
            coalesce(avatar_url, '')::text AS avatar_url,
            ROLE,
            status,
            joined_at,
            last_login_at
`

type CreateIdentityUserParams struct {
	Name      string
	Email     string
	AvatarUrl string
}

type CreateIdentityUserRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) CreateIdentityUser(ctx context.Context, arg CreateIdentityUserParams) (CreateIdentityUserRow, error) {
	row := q.db.QueryRow(ctx, createIdentityUser, arg.Name, arg.Email, arg.AvatarUrl)
	var i CreateIdentityUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createInitialAdmin = `-- name: CreateInitialAdmin :execresult
INSERT INTO users (name, email, password_hash, ROLE, status)
    VALUES ($1, $2, $3, 'admin', 'active')
`

type CreateInitialAdminParams struct {
	Name         string
	Email        string
	PasswordHash *string
}

func (q *Queries) CreateInitialAdmin(ctx context.Context, arg CreateInitialAdminParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createInitialAdmin, arg.Name, arg.Email, arg.PasswordHash)
}

const createLoginState = `-- name: CreateLoginState :execresult
INSERT INTO oauth_login_states (state_hash, connection_id, authorization_request_id, purpose, expires_at)
    VALUES ($1, $2, NULLIF ($3::text, '')::uuid,
	$4, $5)
`

type CreateLoginStateParams struct {
	StateHash              string
	ConnectionID           string
	AuthorizationRequestID string
	Purpose                string
	ExpiresAt              time.Time
}

func (q *Queries) CreateLoginState(ctx context.Context, arg CreateLoginStateParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createLoginState,
		arg.StateHash,
		arg.ConnectionID,
		arg.AuthorizationRequestID,
		arg.Purpose,
		arg.ExpiresAt,
	)
}

const createToken = `-- name: CreateToken :execresult
INSERT INTO oauth_tokens (user_id, client_id, access_token_hash, refresh_token_hash, access_expires_at, refresh_expires_at)
    VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTokenParams struct {
	UserID           string
	ClientID         string
	AccessTokenHash  string
	RefreshTokenHash string
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createToken,
		arg.UserID,
		arg.ClientID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, ROLE, password_hash)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, name, email, coalesce(avatar_url, '')::text AS avatar_url, ROLE, status, joined_at, last_login_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	Role         string
	PasswordHash *string
}

type CreateUserRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAuthorizationCode = `-- name: GetAuthorizationCode :one
SELECT
    id,
    user_id,
    client_id,
    redirect_uri,
    code_challenge,
    expires_at,
    redeemed_at
FROM
    oauth_authorization_codes
WHERE
    code_hash = $1
`

type GetAuthorizationCodeRow struct {
	ID            string
	UserID        string
	ClientID      string
	RedirectUri   string
	CodeChallenge string
	ExpiresAt     time.Time
	RedeemedAt    *time.Time
}

func (q *Queries) GetAuthorizationCode(ctx context.Context, codeHash string) (GetAuthorizationCodeRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCode, codeHash)
	var i GetAuthorizationCodeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.RedeemedAt,
	)
	return i, err
}

const getAuthorizationRequest = `-- name: GetAuthorizationRequest :one
SELECT
    id,
    client_id,
    redirect_uri,
    state,
    code_challenge,
    code_challenge_method,
    expires_at,
    completed_at
FROM
    oauth_authorization_requests
WHERE
    id = $1
`

type GetAuthorizationRequestRow struct {
	ID                  string
	ClientID            string
	RedirectUri         string
	State               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           time.Time
	CompletedAt         *time.Time
}

func (q *Queries) GetAuthorizationRequest(ctx context.Context, id string) (GetAuthorizationRequestRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizationRequest, id)
	var i GetAuthorizationRequestRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.CompletedAt,
	)
	return i, err
}

const getBrowserUser = `-- name: GetBrowserUser :one
SELECT
    u.id,
    u.name,
    u.email,
    coalesce(u.avatar_url, '')::text AS avatar_url,
    u.role,
    u.status,
    u.joined_at,
    u.last_login_at,
    s.authentication_method
FROM
    browser_sessions s
    JOIN users u ON u.id = s.user_id
WHERE
    s.token_hash = $1
    AND s.revoked_at IS NULL
    AND s.expires_at > now()
    AND u.status = 'active'
    AND u.deleted_at IS NULL
`

type GetBrowserUserRow struct {
	ID                   string
	Name                 string
	Email                string
	AvatarUrl            string
	Role                 string
	Status               string
	JoinedAt             time.Time
	LastLoginAt          *time.Time
	AuthenticationMethod string
}

func (q *Queries) GetBrowserUser(ctx context.Context, tokenHash string) (GetBrowserUserRow, error) {
	row := q.db.QueryRow(ctx, getBrowserUser, tokenHash)
	var i GetBrowserUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
		&i.AuthenticationMethod,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT
    id
FROM
    GROUPS
WHERE
    id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetGroup(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	err := row.Scan(&id)
	return id, err
}

const getIdentityUser = `-- name: GetIdentityUser :one
SELECT
    u.id,
    u.name,
    u.email,
    coalesce(u.avatar_url, '')::text AS avatar_url,
    u.role,
    u.status,
    u.joined_at,
    u.last_login_at
FROM
    user_identities i
    JOIN users u ON u.id = i.user_id
WHERE
    i.provider = $1
    AND i.issuer = $2
    AND i.provider_subject = $3
    AND i.deleted_at IS NULL
    AND u.deleted_at IS NULL
`

type GetIdentityUserParams struct {
	Provider        string
	Issuer          string
	ProviderSubject string
}

type GetIdentityUserRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) GetIdentityUser(ctx context.Context, arg GetIdentityUserParams) (GetIdentityUserRow, error) {
	row := q.db.QueryRow(ctx, getIdentityUser, arg.Provider, arg.Issuer, arg.ProviderSubject)
	var i GetIdentityUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getPasswordUser = `-- name: GetPasswordUser :one
SELECT
    id,
    name,
    email,
    coalesce(avatar_url, '')::text AS avatar_url,
    ROLE,
    status,
    joined_at,
    last_login_at,
    password_hash
FROM
    users
WHERE
    lower(email) = $1
    AND ROLE = 'admin'
    AND status = 'active'
    AND deleted_at IS NULL
    AND password_hash IS NOT NULL
`

type GetPasswordUserRow struct {
	ID           string
	Name         string
	Email        string
	AvatarUrl    string
	Role         string
	Status       string
	JoinedAt     time.Time
	LastLoginAt  *time.Time
	PasswordHash *string
}

func (q *Queries) GetPasswordUser(ctx context.Context, email string) (GetPasswordUserRow, error) {
	row := q.db.QueryRow(ctx, getPasswordUser, email)
	var i GetPasswordUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
	)
	return i, err
}

const getTokenUser = `-- name: GetTokenUser :one
SELECT
    u.id,
    u.name,
    u.email,
    coalesce(u.avatar_url, '')::text AS avatar_url,
    u.role,
    u.status,
    u.joined_at,
    u.last_login_at
FROM
    oauth_tokens t
    JOIN users u ON u.id = t.user_id
WHERE
    t.access_token_hash = $1
    AND t.revoked_at IS NULL
    AND t.access_expires_at > now()
    AND u.status = 'active'
    AND u.deleted_at IS NULL
`

type GetTokenUserRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) GetTokenUser(ctx context.Context, accessTokenHash string) (GetTokenUserRow, error) {
	row := q.db.QueryRow(ctx, getTokenUser, accessTokenHash)
	var i GetTokenUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    name,
    email,
    coalesce(avatar_url, '')::text AS avatar_url,
    ROLE,
    status,
    joined_at,
    last_login_at
FROM
    users
WHERE
    id = $1
    AND deleted_at IS NULL
`

type GetUserRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    name,
    email,
    coalesce(avatar_url, '')::text AS avatar_url,
    ROLE,
    status,
    joined_at,
    last_login_at
FROM
    users
WHERE
    lower(email) = lower($1)
    AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    name,
    email,
    coalesce(avatar_url, '')::text AS avatar_url,
    ROLE,
    status,
    joined_at,
    last_login_at
FROM
    users
WHERE
    deleted_at IS NULL
ORDER BY
    joined_at DESC
`

type ListUsersRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBillingGroup = `-- name: LockBillingGroup :one
SELECT
    billing_group_id
FROM
    users
WHERE
    id = $1
    AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockBillingGroup(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, lockBillingGroup, id)
	var billing_group_id *string
	err := row.Scan(&billing_group_id)
	return billing_group_id, err
}

const lockGroups = `-- name: LockGroups :execresult
SELECT
    pg_advisory_xact_lock(741209)
`

func (q *Queries) LockGroups(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, lockGroups)
}

const lockInitialAdmin = `-- name: LockInitialAdmin :execresult
SELECT
    pg_advisory_xact_lock(hashtext('monkeyai:initial-admin'))
`

func (q *Queries) LockInitialAdmin(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, lockInitialAdmin)
}

const redeemAuthorizationCode = `-- name: RedeemAuthorizationCode :execresult
UPDATE
    oauth_authorization_codes
SET
    redeemed_at = now()
WHERE
    id = $1
    AND redeemed_at IS NULL
    AND expires_at > now()
`

func (q *Queries) RedeemAuthorizationCode(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, redeemAuthorizationCode, id)
}

const revokeBrowserSession = `-- name: RevokeBrowserSession :execresult
UPDATE
    browser_sessions
SET
    revoked_at = now()
WHERE
    token_hash = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeBrowserSession(ctx context.Context, tokenHash string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, revokeBrowserSession, tokenHash)
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE
    oauth_tokens
SET
    revoked_at = now()
WHERE
    refresh_token_hash = $1
    AND client_id = $2
    AND revoked_at IS NULL
    AND refresh_expires_at > now()
RETURNING
    user_id
`

type RevokeRefreshTokenParams struct {
	RefreshTokenHash string
	ClientID         string
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, arg.RefreshTokenHash, arg.ClientID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const revokeToken = `-- name: RevokeToken :execresult
UPDATE
    oauth_tokens
SET
    revoked_at = now()
WHERE
    client_id = $2
    AND revoked_at IS NULL
    AND (access_token_hash = $1
        OR refresh_token_hash = $1)
`

type RevokeTokenParams struct {
	AccessTokenHash string
	ClientID        string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, revokeToken, arg.AccessTokenHash, arg.ClientID)
}

const searchUsers = `-- name: SearchUsers :many
SELECT
    id,
    name,
    email
FROM
    users
WHERE
    status = 'active'
    AND deleted_at IS NULL
    AND id <> $1
    AND (strpos(lower(name), lower($2)) > 0
        OR strpos(lower(email), lower($2)) > 0)
ORDER BY
    lower(name),
    id
LIMIT $3
`

type SearchUsersParams struct {
	ID    string
	Lower string
	Limit int32
}

type SearchUsersRow struct {
	ID    string
	Name  string
	Email string
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.ID, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBillingGroup = `-- name: SetBillingGroup :execresult
UPDATE
    users
SET
    billing_group_id = $2,
    updated_at = now()
WHERE
    id = $1
`

type SetBillingGroupParams struct {
	ID             string
	BillingGroupID *string
}

func (q *Queries) SetBillingGroup(ctx context.Context, arg SetBillingGroupParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setBillingGroup, arg.ID, arg.BillingGroupID)
}

const touchLogin = `-- name: TouchLogin :execresult
UPDATE
    users
SET
    last_login_at = now(),
    updated_at = now()
WHERE
    id = $1
`

func (q *Queries) TouchLogin(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, touchLogin, id)
}

const updateIdentityUser = `-- name: UpdateIdentityUser :one
UPDATE
    users
SET
    name = $1,
    avatar_url = NULLIF ($2::text, ''),
    last_login_at = now(),
    updated_at = now()
WHERE
    id = $3
RETURNING
    id,
    name,
    email,
    coalesce(avatar_url, '')::text AS avatar_url,
    ROLE,
    status,
    joined_at,
    last_login_at
`

type UpdateIdentityUserParams struct {
	Name      string
	AvatarUrl string
	ID        string
}

type UpdateIdentityUserRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) UpdateIdentityUser(ctx context.Context, arg UpdateIdentityUserParams) (UpdateIdentityUserRow, error) {
	row := q.db.QueryRow(ctx, updateIdentityUser, arg.Name, arg.AvatarUrl, arg.ID)
	var i UpdateIdentityUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE
    users
SET
    name = $1,
    ROLE = $2,
    status = $3,
    disabled_at = $4,
    password_hash = CASE WHEN $5::text = '' THEN
        password_hash
    ELSE
        $5::text
    END,
    updated_at = now()
WHERE
    id = $6
    AND deleted_at IS NULL
RETURNING
    id,
    name,
    email,
    coalesce(avatar_url, '')::text AS avatar_url,
    ROLE,
    status,
    joined_at,
    last_login_at
`

type UpdateUserParams struct {
	Name         string
	Role         string
	Status       string
	DisabledAt   *time.Time
	PasswordHash string
	ID           string
}

type UpdateUserRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   string
	Role        string
	Status      string
	JoinedAt    time.Time
	LastLoginAt *time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Role,
		arg.Status,
		arg.DisabledAt,
		arg.PasswordHash,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertIdentity = `-- name: UpsertIdentity :execresult
INSERT INTO user_identities (user_id, provider, issuer, provider_subject, username, email, avatar_url)
    VALUES ($1, $2, $3, $4,
	NULLIF ($5::text, ''), NULLIF($6::text,''), NULLIF ($7::text, ''))
`

type UpsertIdentityParams struct {
	UserID            string
	Provider          string
	Issuer            string
	ProviderSubject   string
	ProviderUsername  string
	ProviderEmail     string
	ProviderAvatarUrl string
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertIdentity,
		arg.UserID,
		arg.Provider,
		arg.Issuer,
		arg.ProviderSubject,
		arg.ProviderUsername,
		arg.ProviderEmail,
		arg.ProviderAvatarUrl,
	)
}
