// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const catalogConnectorLinks = `-- name: CatalogConnectorLinks :many
SELECT
    to_jsonb (t)
FROM
    expert_connectors t
ORDER BY
    expert_id
`

func (q *Queries) CatalogConnectorLinks(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, catalogConnectorLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogConnectors = `-- name: CatalogConnectors :many
SELECT
    to_jsonb (t)
FROM
    connectors t
WHERE
    deleted_at IS NULL
`

func (q *Queries) CatalogConnectors(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, catalogConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogExperts = `-- name: CatalogExperts :many
SELECT
    to_jsonb (t)
FROM
    experts t
WHERE
    deleted_at IS NULL
`

func (q *Queries) CatalogExperts(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, catalogExperts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogRuleLinks = `-- name: CatalogRuleLinks :many
SELECT
    to_jsonb (t)
FROM
    expert_rules t
ORDER BY
    expert_id
`

func (q *Queries) CatalogRuleLinks(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, catalogRuleLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogRules = `-- name: CatalogRules :many
SELECT
    to_jsonb (t)
FROM
    rules t
WHERE
    deleted_at IS NULL
`

func (q *Queries) CatalogRules(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, catalogRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogSkillLinks = `-- name: CatalogSkillLinks :many
SELECT
    to_jsonb (t)
FROM
    expert_skills t
ORDER BY
    expert_id
`

func (q *Queries) CatalogSkillLinks(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, catalogSkillLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogSkills = `-- name: CatalogSkills :many
SELECT
    to_jsonb (t)
FROM
    skills t
WHERE
    deleted_at IS NULL
`

func (q *Queries) CatalogSkills(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, catalogSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
WITH RECURSIVE user_groups (
    group_id
) AS (
    SELECT
        id
    FROM
        GROUPS
    WHERE
        deleted_at IS NULL
        AND id IN (
            SELECT
                group_id
            FROM
                group_users
            WHERE
                user_id = $1
                AND removed_at IS NULL)
        UNION
        SELECT
            parent.id
        FROM
            GROUPS g
            JOIN user_groups ug ON ug.group_id = g.id
            JOIN GROUPS parent ON parent.id = g.parent_id
        WHERE
            g.deleted_at IS NULL
            AND parent.deleted_at IS NULL
)
SELECT
    jsonb_build_object('kind', resource_type, 'id', resource_id, 'required',
	bool_or(usage_requirement = 'required'))
FROM
    resource_access_grants rag
WHERE
    (rag.all_users AND EXISTS (
        SELECT 1 FROM users u WHERE u.id = $1 AND u.status = 'active' AND u.deleted_at IS NULL
    ))
    OR rag.user_id = $1
    OR rag.group_id IN (
        SELECT
            group_id
        FROM
            user_groups)
GROUP BY
    resource_type,
    resource_id
`

func (q *Queries) ListGrants(ctx context.Context, userID *string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillTags = `-- name: ListSkillTags :many
SELECT
    jsonb_build_object('id', t.id, 'name', t.name)
FROM
    tags t
    JOIN resource_tags rt ON rt.tag_id = t.id
WHERE
    rt.resource_type = 'skill'
    AND rt.resource_id = $1
    AND t.deleted_at IS NULL
ORDER BY
    t.id
`

func (q *Queries) ListSkillTags(ctx context.Context, resourceID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listSkillTags, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
