// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Model struct {
	ID               string
	OwnershipType    string
	OwnerUserID      string
	ModelID          string
	DisplayName      string
	Protocol         string
	BaseUrl          string
	ApiKey           string
	AdvancedConfig   []byte
	CreditMultiplier float64
	Enabled          bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
}
