// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const createResource = `-- name: CreateResource :exec
INSERT INTO rules (name, content, id, owner_user_id, ownership_type)
    VALUES (
        CASE WHEN $1::jsonb ? 'name' THEN
            ($1::jsonb ->> 'name')::text
        ELSE
            NULL
        END, CASE WHEN $1::jsonb ? 'content' THEN
            ($1::jsonb ->> 'content')::text
        ELSE
            NULL
	END, ($1::jsonb ->> 'id')::uuid, ($1::jsonb ->>
	    'actor_id')::uuid, COALESCE($1::jsonb ->> 'ownership_type', 'system'))
`

func (q *Queries) CreateResource(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, createResource, data)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
UPDATE
    rules
SET
    deleted_at = now(),
    updated_at = now(),
    revision = revision + 1
WHERE
    id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT
    to_jsonb (t)
FROM
    rules t
WHERE
    id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetResource(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const listReferences = `-- name: ListReferences :many
SELECT
    jsonb_build_object('id', e.id, 'name', e.name)
FROM
    experts e
    JOIN expert_rules x ON x.expert_id = e.id
WHERE
    x.rule_id = $1
    AND e.deleted_at IS NULL
`

func (q *Queries) ListReferences(ctx context.Context, ruleID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listReferences, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT
    to_jsonb (t)
FROM
    rules t
WHERE
    deleted_at IS NULL
ORDER BY
    lower(name),
    id
`

func (q *Queries) ListResources(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResource = `-- name: LockResource :one
SELECT
    to_jsonb (t)
FROM
    rules t
WHERE
    id = $1
    AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockResource(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockResource, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const pageResources = `-- name: PageResources :many
SELECT
    to_jsonb (t)
FROM
    rules t
WHERE
    deleted_at IS NULL
    AND ($1::jsonb ->> 'ownership' = ''
        OR t.ownership_type = $1::jsonb ->> 'ownership')
    AND name ILIKE '%' || ($1::jsonb ->> 'search') || '%'
    AND id::text > $1::jsonb ->> 'cursor'
ORDER BY
    id
LIMIT ($1::jsonb ->> 'limit')::integer
`

func (q *Queries) PageResources(ctx context.Context, filter []byte) ([][]byte, error) {
	rows, err := q.db.Query(ctx, pageResources, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchResource = `-- name: TouchResource :exec
UPDATE
    rules
SET
    updated_at = now(),
    revision = revision + 1
WHERE
    id = $1
`

func (q *Queries) TouchResource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchResource, id)
	return err
}

const updateResource = `-- name: UpdateResource :exec
UPDATE
    rules
SET
    name = CASE WHEN $1::jsonb ? 'name' THEN
        ($1::jsonb ->> 'name')::text
    ELSE
        name
    END,
    content = CASE WHEN $1::jsonb ? 'content' THEN
        ($1::jsonb ->> 'content')::text
    ELSE
        content
    END,
    revision = revision + 1,
    updated_at = now()
WHERE
    id = ($1::jsonb ->> 'id')::uuid
`

func (q *Queries) UpdateResource(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateResource, data)
	return err
}
