// Code generated by ent, DO NOT EDIT.

package endpoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldUserID, v))
}

// MachineID applies equality check predicate on the "machine_id" field. It's identical to MachineIDEQ.
func MachineID(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldMachineID, v))
}

// DeviceName applies equality check predicate on the "device_name" field. It's identical to DeviceNameEQ.
func DeviceName(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldDeviceName, v))
}

// OsVersion applies equality check predicate on the "os_version" field. It's identical to OsVersionEQ.
func OsVersion(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldOsVersion, v))
}

// Arch applies equality check predicate on the "arch" field. It's identical to ArchEQ.
func Arch(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldArch, v))
}

// ClientVersion applies equality check predicate on the "client_version" field. It's identical to ClientVersionEQ.
func ClientVersion(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldClientVersion, v))
}

// ProtocolVersion applies equality check predicate on the "protocol_version" field. It's identical to ProtocolVersionEQ.
func ProtocolVersion(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldProtocolVersion, v))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldAlias, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldUserID, vs...))
}

// MachineIDEQ applies the EQ predicate on the "machine_id" field.
func MachineIDEQ(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldMachineID, v))
}

// MachineIDNEQ applies the NEQ predicate on the "machine_id" field.
func MachineIDNEQ(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldMachineID, v))
}

// MachineIDIn applies the In predicate on the "machine_id" field.
func MachineIDIn(vs ...uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldMachineID, vs...))
}

// MachineIDNotIn applies the NotIn predicate on the "machine_id" field.
func MachineIDNotIn(vs ...uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldMachineID, vs...))
}

// MachineIDGT applies the GT predicate on the "machine_id" field.
func MachineIDGT(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldMachineID, v))
}

// MachineIDGTE applies the GTE predicate on the "machine_id" field.
func MachineIDGTE(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldMachineID, v))
}

// MachineIDLT applies the LT predicate on the "machine_id" field.
func MachineIDLT(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldMachineID, v))
}

// MachineIDLTE applies the LTE predicate on the "machine_id" field.
func MachineIDLTE(v uuid.UUID) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldMachineID, v))
}

// DeviceNameEQ applies the EQ predicate on the "device_name" field.
func DeviceNameEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldDeviceName, v))
}

// DeviceNameNEQ applies the NEQ predicate on the "device_name" field.
func DeviceNameNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldDeviceName, v))
}

// DeviceNameIn applies the In predicate on the "device_name" field.
func DeviceNameIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldDeviceName, vs...))
}

// DeviceNameNotIn applies the NotIn predicate on the "device_name" field.
func DeviceNameNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldDeviceName, vs...))
}

// DeviceNameGT applies the GT predicate on the "device_name" field.
func DeviceNameGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldDeviceName, v))
}

// DeviceNameGTE applies the GTE predicate on the "device_name" field.
func DeviceNameGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldDeviceName, v))
}

// DeviceNameLT applies the LT predicate on the "device_name" field.
func DeviceNameLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldDeviceName, v))
}

// DeviceNameLTE applies the LTE predicate on the "device_name" field.
func DeviceNameLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldDeviceName, v))
}

// DeviceNameContains applies the Contains predicate on the "device_name" field.
func DeviceNameContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldDeviceName, v))
}

// DeviceNameHasPrefix applies the HasPrefix predicate on the "device_name" field.
func DeviceNameHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldDeviceName, v))
}

// DeviceNameHasSuffix applies the HasSuffix predicate on the "device_name" field.
func DeviceNameHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldDeviceName, v))
}

// DeviceNameEqualFold applies the EqualFold predicate on the "device_name" field.
func DeviceNameEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldDeviceName, v))
}

// DeviceNameContainsFold applies the ContainsFold predicate on the "device_name" field.
func DeviceNameContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldDeviceName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v Platform) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v Platform) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...Platform) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...Platform) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldPlatform, vs...))
}

// OsVersionEQ applies the EQ predicate on the "os_version" field.
func OsVersionEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldOsVersion, v))
}

// OsVersionNEQ applies the NEQ predicate on the "os_version" field.
func OsVersionNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldOsVersion, v))
}

// OsVersionIn applies the In predicate on the "os_version" field.
func OsVersionIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldOsVersion, vs...))
}

// OsVersionNotIn applies the NotIn predicate on the "os_version" field.
func OsVersionNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldOsVersion, vs...))
}

// OsVersionGT applies the GT predicate on the "os_version" field.
func OsVersionGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldOsVersion, v))
}

// OsVersionGTE applies the GTE predicate on the "os_version" field.
func OsVersionGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldOsVersion, v))
}

// OsVersionLT applies the LT predicate on the "os_version" field.
func OsVersionLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldOsVersion, v))
}

// OsVersionLTE applies the LTE predicate on the "os_version" field.
func OsVersionLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldOsVersion, v))
}

// OsVersionContains applies the Contains predicate on the "os_version" field.
func OsVersionContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldOsVersion, v))
}

// OsVersionHasPrefix applies the HasPrefix predicate on the "os_version" field.
func OsVersionHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldOsVersion, v))
}

// OsVersionHasSuffix applies the HasSuffix predicate on the "os_version" field.
func OsVersionHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldOsVersion, v))
}

// OsVersionEqualFold applies the EqualFold predicate on the "os_version" field.
func OsVersionEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldOsVersion, v))
}

// OsVersionContainsFold applies the ContainsFold predicate on the "os_version" field.
func OsVersionContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldOsVersion, v))
}

// ArchEQ applies the EQ predicate on the "arch" field.
func ArchEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldArch, v))
}

// ArchNEQ applies the NEQ predicate on the "arch" field.
func ArchNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldArch, v))
}

// ArchIn applies the In predicate on the "arch" field.
func ArchIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldArch, vs...))
}

// ArchNotIn applies the NotIn predicate on the "arch" field.
func ArchNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldArch, vs...))
}

// ArchGT applies the GT predicate on the "arch" field.
func ArchGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldArch, v))
}

// ArchGTE applies the GTE predicate on the "arch" field.
func ArchGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldArch, v))
}

// ArchLT applies the LT predicate on the "arch" field.
func ArchLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldArch, v))
}

// ArchLTE applies the LTE predicate on the "arch" field.
func ArchLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldArch, v))
}

// ArchContains applies the Contains predicate on the "arch" field.
func ArchContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldArch, v))
}

// ArchHasPrefix applies the HasPrefix predicate on the "arch" field.
func ArchHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldArch, v))
}

// ArchHasSuffix applies the HasSuffix predicate on the "arch" field.
func ArchHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldArch, v))
}

// ArchEqualFold applies the EqualFold predicate on the "arch" field.
func ArchEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldArch, v))
}

// ArchContainsFold applies the ContainsFold predicate on the "arch" field.
func ArchContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldArch, v))
}

// ClientVersionEQ applies the EQ predicate on the "client_version" field.
func ClientVersionEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldClientVersion, v))
}

// ClientVersionNEQ applies the NEQ predicate on the "client_version" field.
func ClientVersionNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldClientVersion, v))
}

// ClientVersionIn applies the In predicate on the "client_version" field.
func ClientVersionIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldClientVersion, vs...))
}

// ClientVersionNotIn applies the NotIn predicate on the "client_version" field.
func ClientVersionNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldClientVersion, vs...))
}

// ClientVersionGT applies the GT predicate on the "client_version" field.
func ClientVersionGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldClientVersion, v))
}

// ClientVersionGTE applies the GTE predicate on the "client_version" field.
func ClientVersionGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldClientVersion, v))
}

// ClientVersionLT applies the LT predicate on the "client_version" field.
func ClientVersionLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldClientVersion, v))
}

// ClientVersionLTE applies the LTE predicate on the "client_version" field.
func ClientVersionLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldClientVersion, v))
}

// ClientVersionContains applies the Contains predicate on the "client_version" field.
func ClientVersionContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldClientVersion, v))
}

// ClientVersionHasPrefix applies the HasPrefix predicate on the "client_version" field.
func ClientVersionHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldClientVersion, v))
}

// ClientVersionHasSuffix applies the HasSuffix predicate on the "client_version" field.
func ClientVersionHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldClientVersion, v))
}

// ClientVersionEqualFold applies the EqualFold predicate on the "client_version" field.
func ClientVersionEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldClientVersion, v))
}

// ClientVersionContainsFold applies the ContainsFold predicate on the "client_version" field.
func ClientVersionContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldClientVersion, v))
}

// ProtocolVersionEQ applies the EQ predicate on the "protocol_version" field.
func ProtocolVersionEQ(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldProtocolVersion, v))
}

// ProtocolVersionNEQ applies the NEQ predicate on the "protocol_version" field.
func ProtocolVersionNEQ(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldProtocolVersion, v))
}

// ProtocolVersionIn applies the In predicate on the "protocol_version" field.
func ProtocolVersionIn(vs ...int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldProtocolVersion, vs...))
}

// ProtocolVersionNotIn applies the NotIn predicate on the "protocol_version" field.
func ProtocolVersionNotIn(vs ...int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldProtocolVersion, vs...))
}

// ProtocolVersionGT applies the GT predicate on the "protocol_version" field.
func ProtocolVersionGT(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldProtocolVersion, v))
}

// ProtocolVersionGTE applies the GTE predicate on the "protocol_version" field.
func ProtocolVersionGTE(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldProtocolVersion, v))
}

// ProtocolVersionLT applies the LT predicate on the "protocol_version" field.
func ProtocolVersionLT(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldProtocolVersion, v))
}

// ProtocolVersionLTE applies the LTE predicate on the "protocol_version" field.
func ProtocolVersionLTE(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldProtocolVersion, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasIsNil applies the IsNil predicate on the "alias" field.
func AliasIsNil() predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIsNull(FieldAlias))
}

// AliasNotNil applies the NotNil predicate on the "alias" field.
func AliasNotNil() predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotNull(FieldAlias))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldAlias, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldStatus, vs...))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotNull(FieldLastSeenAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Endpoint {
	return predicate.Endpoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Endpoint {
	return predicate.Endpoint(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Endpoint) predicate.Endpoint {
	return predicate.Endpoint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Endpoint) predicate.Endpoint {
	return predicate.Endpoint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Endpoint) predicate.Endpoint {
	return predicate.Endpoint(sql.NotPredicates(p))
}
