BEGIN;

DROP TABLE api_keys;
DROP TABLE oauth_tokens;
DROP TABLE oauth_authorization_codes;
DROP TABLE oauth_login_states;
DROP TABLE oauth_authorization_requests;
DROP TABLE browser_sessions;
DROP TABLE email_code_deliveries;
DROP TABLE email_codes;
DROP TABLE audits;
DROP TABLE credit_ledger_entries;
DROP FUNCTION billing_immutable_ledger();
DROP TABLE billing_migration_issues;
DROP TABLE wallet_billing_records;
DROP TABLE wallet_user_bindings;
DROP TABLE billing_transactions;
DROP TABLE credit_accounts;
DROP TABLE billing_quotas;
DROP TABLE mcp_tool_calls;
DROP TABLE model_calls;
DROP TABLE sessions;
DROP TABLE expert_skills;
DROP TABLE expert_rules;
DROP TABLE expert_connectors;
DROP TABLE resource_tags;
DROP TABLE resource_access_grants;
DROP TABLE experts;
DROP TABLE connector_oauth_requests;
DROP TABLE mcp_tools;
DROP TABLE connector_credentials;
DROP TABLE connectors;
DROP TABLE rules;
DROP TABLE skills;
DROP TABLE tags;
DROP TABLE models;
DROP TABLE settings;
DROP TABLE group_users;
ALTER TABLE users DROP CONSTRAINT users_billing_group_id_fkey;
DROP TABLE groups;
DROP TABLE user_identities;
DROP TABLE users;

COMMIT;
