BEGIN;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM billing_transactions) OR EXISTS(SELECT 1 FROM credit_accounts GROUP BY user_id HAVING count(*)>1) THEN RAISE EXCEPTION '已有计费交易或周期历史，不允许破坏性回滚'; END IF; END $$;
DROP TRIGGER credit_ledger_immutable ON credit_ledger_entries;
DROP FUNCTION billing_immutable_ledger();
DROP TABLE wallet_billing_records;
DROP TABLE wallet_user_bindings;
DROP TABLE billing_migration_issues;
ALTER TABLE credit_ledger_entries DROP COLUMN transaction_id,DROP COLUMN event_key,DROP COLUMN sequence,DROP COLUMN user_name,DROP COLUMN user_email,DROP COLUMN group_id,DROP COLUMN mode,DROP COLUMN reverses_id;
DROP TABLE billing_transactions;
DROP INDEX credit_accounts_user_period_key;
ALTER TABLE credit_accounts DROP CONSTRAINT credit_accounts_amount_check,DROP COLUMN frozen,DROP COLUMN quota,DROP COLUMN group_id,DROP COLUMN sequence;
ALTER TABLE credit_accounts ADD CONSTRAINT credit_accounts_user_id_key UNIQUE(user_id);
ALTER TABLE users DROP COLUMN billing_group_id;
ALTER TABLE settings DROP COLUMN revision;
COMMIT;
