// Code generated by ent, DO NOT EDIT.

package mcpupstream

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mcpupstream type in the database.
	Label = "mcp_upstream"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldHealthStatus holds the string denoting the health_status field in the database.
	FieldHealthStatus = "health_status"
	// FieldSyncStatus holds the string denoting the sync_status field in the database.
	FieldSyncStatus = "sync_status"
	// FieldHealthCheckedAt holds the string denoting the health_checked_at field in the database.
	FieldHealthCheckedAt = "health_checked_at"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the mcpupstream in the database.
	Table = "mcp_upstreams"
)

// Columns holds all SQL columns for mcpupstream fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSlug,
	FieldScope,
	FieldUserID,
	FieldType,
	FieldURL,
	FieldHeaders,
	FieldDescription,
	FieldEnabled,
	FieldHealthStatus,
	FieldSyncStatus,
	FieldHealthCheckedAt,
	FieldLastSyncedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultScope holds the default value on creation for the "scope" field.
	DefaultScope string
	// ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	ScopeValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultHealthStatus holds the default value on creation for the "health_status" field.
	DefaultHealthStatus string
	// HealthStatusValidator is a validator for the "health_status" field. It is called by the builders before save.
	HealthStatusValidator func(string) error
	// DefaultSyncStatus holds the default value on creation for the "sync_status" field.
	DefaultSyncStatus string
	// SyncStatusValidator is a validator for the "sync_status" field. It is called by the builders before save.
	SyncStatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the MCPUpstream queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByHealthStatus orders the results by the health_status field.
func ByHealthStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthStatus, opts...).ToFunc()
}

// BySyncStatus orders the results by the sync_status field.
func BySyncStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncStatus, opts...).ToFunc()
}

// ByHealthCheckedAt orders the results by the health_checked_at field.
func ByHealthCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthCheckedAt, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
