// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/endpoint"
	"github.com/chaitin/MonkeyCode/backend/db/user"
	"github.com/google/uuid"
)

// EndpointCreate is the builder for creating a Endpoint entity.
type EndpointCreate struct {
	config
	mutation *EndpointMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *EndpointCreate) SetUserID(v uuid.UUID) *EndpointCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetMachineID sets the "machine_id" field.
func (_c *EndpointCreate) SetMachineID(v uuid.UUID) *EndpointCreate {
	_c.mutation.SetMachineID(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *EndpointCreate) SetDeviceName(v string) *EndpointCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *EndpointCreate) SetPlatform(v endpoint.Platform) *EndpointCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetOsVersion sets the "os_version" field.
func (_c *EndpointCreate) SetOsVersion(v string) *EndpointCreate {
	_c.mutation.SetOsVersion(v)
	return _c
}

// SetArch sets the "arch" field.
func (_c *EndpointCreate) SetArch(v string) *EndpointCreate {
	_c.mutation.SetArch(v)
	return _c
}

// SetClientVersion sets the "client_version" field.
func (_c *EndpointCreate) SetClientVersion(v string) *EndpointCreate {
	_c.mutation.SetClientVersion(v)
	return _c
}

// SetProtocolVersion sets the "protocol_version" field.
func (_c *EndpointCreate) SetProtocolVersion(v int) *EndpointCreate {
	_c.mutation.SetProtocolVersion(v)
	return _c
}

// SetNillableProtocolVersion sets the "protocol_version" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableProtocolVersion(v *int) *EndpointCreate {
	if v != nil {
		_c.SetProtocolVersion(*v)
	}
	return _c
}

// SetAlias sets the "alias" field.
func (_c *EndpointCreate) SetAlias(v string) *EndpointCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableAlias(v *string) *EndpointCreate {
	if v != nil {
		_c.SetAlias(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EndpointCreate) SetStatus(v endpoint.Status) *EndpointCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableStatus(v *endpoint.Status) *EndpointCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *EndpointCreate) SetLastSeenAt(v time.Time) *EndpointCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableLastSeenAt(v *time.Time) *EndpointCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EndpointCreate) SetCreatedAt(v time.Time) *EndpointCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableCreatedAt(v *time.Time) *EndpointCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EndpointCreate) SetUpdatedAt(v time.Time) *EndpointCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableUpdatedAt(v *time.Time) *EndpointCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EndpointCreate) SetID(v uuid.UUID) *EndpointCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableID(v *uuid.UUID) *EndpointCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *EndpointCreate) SetUser(v *User) *EndpointCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the EndpointMutation object of the builder.
func (_c *EndpointCreate) Mutation() *EndpointMutation {
	return _c.mutation
}

// Save creates the Endpoint in the database.
func (_c *EndpointCreate) Save(ctx context.Context) (*Endpoint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EndpointCreate) SaveX(ctx context.Context) *Endpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EndpointCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EndpointCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EndpointCreate) defaults() {
	if _, ok := _c.mutation.ProtocolVersion(); !ok {
		v := endpoint.DefaultProtocolVersion
		_c.mutation.SetProtocolVersion(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := endpoint.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := endpoint.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := endpoint.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := endpoint.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EndpointCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`db: missing required field "Endpoint.user_id"`)}
	}
	if _, ok := _c.mutation.MachineID(); !ok {
		return &ValidationError{Name: "machine_id", err: errors.New(`db: missing required field "Endpoint.machine_id"`)}
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`db: missing required field "Endpoint.device_name"`)}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := endpoint.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`db: validator failed for field "Endpoint.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`db: missing required field "Endpoint.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := endpoint.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`db: validator failed for field "Endpoint.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OsVersion(); !ok {
		return &ValidationError{Name: "os_version", err: errors.New(`db: missing required field "Endpoint.os_version"`)}
	}
	if _, ok := _c.mutation.Arch(); !ok {
		return &ValidationError{Name: "arch", err: errors.New(`db: missing required field "Endpoint.arch"`)}
	}
	if _, ok := _c.mutation.ClientVersion(); !ok {
		return &ValidationError{Name: "client_version", err: errors.New(`db: missing required field "Endpoint.client_version"`)}
	}
	if _, ok := _c.mutation.ProtocolVersion(); !ok {
		return &ValidationError{Name: "protocol_version", err: errors.New(`db: missing required field "Endpoint.protocol_version"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`db: missing required field "Endpoint.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := endpoint.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "Endpoint.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "Endpoint.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "Endpoint.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`db: missing required edge "Endpoint.user"`)}
	}
	return nil
}

func (_c *EndpointCreate) sqlSave(ctx context.Context) (*Endpoint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EndpointCreate) createSpec() (*Endpoint, *sqlgraph.CreateSpec) {
	var (
		_node = &Endpoint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(endpoint.Table, sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.MachineID(); ok {
		_spec.SetField(endpoint.FieldMachineID, field.TypeUUID, value)
		_node.MachineID = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(endpoint.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(endpoint.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.OsVersion(); ok {
		_spec.SetField(endpoint.FieldOsVersion, field.TypeString, value)
		_node.OsVersion = value
	}
	if value, ok := _c.mutation.Arch(); ok {
		_spec.SetField(endpoint.FieldArch, field.TypeString, value)
		_node.Arch = value
	}
	if value, ok := _c.mutation.ClientVersion(); ok {
		_spec.SetField(endpoint.FieldClientVersion, field.TypeString, value)
		_node.ClientVersion = value
	}
	if value, ok := _c.mutation.ProtocolVersion(); ok {
		_spec.SetField(endpoint.FieldProtocolVersion, field.TypeInt, value)
		_node.ProtocolVersion = value
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(endpoint.FieldAlias, field.TypeString, value)
		_node.Alias = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(endpoint.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(endpoint.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(endpoint.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(endpoint.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   endpoint.UserTable,
			Columns: []string{endpoint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Endpoint.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EndpointUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *EndpointCreate) OnConflict(opts ...sql.ConflictOption) *EndpointUpsertOne {
	_c.conflict = opts
	return &EndpointUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Endpoint.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EndpointCreate) OnConflictColumns(columns ...string) *EndpointUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EndpointUpsertOne{
		create: _c,
	}
}

type (
	// EndpointUpsertOne is the builder for "upsert"-ing
	//  one Endpoint node.
	EndpointUpsertOne struct {
		create *EndpointCreate
	}

	// EndpointUpsert is the "OnConflict" setter.
	EndpointUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *EndpointUpsert) SetUserID(v uuid.UUID) *EndpointUpsert {
	u.Set(endpoint.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateUserID() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldUserID)
	return u
}

// SetMachineID sets the "machine_id" field.
func (u *EndpointUpsert) SetMachineID(v uuid.UUID) *EndpointUpsert {
	u.Set(endpoint.FieldMachineID, v)
	return u
}

// UpdateMachineID sets the "machine_id" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateMachineID() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldMachineID)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *EndpointUpsert) SetDeviceName(v string) *EndpointUpsert {
	u.Set(endpoint.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateDeviceName() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldDeviceName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *EndpointUpsert) SetPlatform(v endpoint.Platform) *EndpointUpsert {
	u.Set(endpoint.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EndpointUpsert) UpdatePlatform() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldPlatform)
	return u
}

// SetOsVersion sets the "os_version" field.
func (u *EndpointUpsert) SetOsVersion(v string) *EndpointUpsert {
	u.Set(endpoint.FieldOsVersion, v)
	return u
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateOsVersion() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldOsVersion)
	return u
}

// SetArch sets the "arch" field.
func (u *EndpointUpsert) SetArch(v string) *EndpointUpsert {
	u.Set(endpoint.FieldArch, v)
	return u
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateArch() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldArch)
	return u
}

// SetClientVersion sets the "client_version" field.
func (u *EndpointUpsert) SetClientVersion(v string) *EndpointUpsert {
	u.Set(endpoint.FieldClientVersion, v)
	return u
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateClientVersion() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldClientVersion)
	return u
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *EndpointUpsert) SetProtocolVersion(v int) *EndpointUpsert {
	u.Set(endpoint.FieldProtocolVersion, v)
	return u
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateProtocolVersion() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldProtocolVersion)
	return u
}

// AddProtocolVersion adds v to the "protocol_version" field.
func (u *EndpointUpsert) AddProtocolVersion(v int) *EndpointUpsert {
	u.Add(endpoint.FieldProtocolVersion, v)
	return u
}

// SetAlias sets the "alias" field.
func (u *EndpointUpsert) SetAlias(v string) *EndpointUpsert {
	u.Set(endpoint.FieldAlias, v)
	return u
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateAlias() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldAlias)
	return u
}

// ClearAlias clears the value of the "alias" field.
func (u *EndpointUpsert) ClearAlias() *EndpointUpsert {
	u.SetNull(endpoint.FieldAlias)
	return u
}

// SetStatus sets the "status" field.
func (u *EndpointUpsert) SetStatus(v endpoint.Status) *EndpointUpsert {
	u.Set(endpoint.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateStatus() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldStatus)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *EndpointUpsert) SetLastSeenAt(v time.Time) *EndpointUpsert {
	u.Set(endpoint.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateLastSeenAt() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldLastSeenAt)
	return u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *EndpointUpsert) ClearLastSeenAt() *EndpointUpsert {
	u.SetNull(endpoint.FieldLastSeenAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *EndpointUpsert) SetCreatedAt(v time.Time) *EndpointUpsert {
	u.Set(endpoint.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateCreatedAt() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EndpointUpsert) SetUpdatedAt(v time.Time) *EndpointUpsert {
	u.Set(endpoint.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EndpointUpsert) UpdateUpdatedAt() *EndpointUpsert {
	u.SetExcluded(endpoint.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Endpoint.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(endpoint.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EndpointUpsertOne) UpdateNewValues() *EndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(endpoint.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Endpoint.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EndpointUpsertOne) Ignore() *EndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EndpointUpsertOne) DoNothing() *EndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EndpointCreate.OnConflict
// documentation for more info.
func (u *EndpointUpsertOne) Update(set func(*EndpointUpsert)) *EndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EndpointUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *EndpointUpsertOne) SetUserID(v uuid.UUID) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateUserID() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateUserID()
	})
}

// SetMachineID sets the "machine_id" field.
func (u *EndpointUpsertOne) SetMachineID(v uuid.UUID) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetMachineID(v)
	})
}

// UpdateMachineID sets the "machine_id" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateMachineID() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateMachineID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *EndpointUpsertOne) SetDeviceName(v string) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateDeviceName() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateDeviceName()
	})
}

// SetPlatform sets the "platform" field.
func (u *EndpointUpsertOne) SetPlatform(v endpoint.Platform) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdatePlatform() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdatePlatform()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *EndpointUpsertOne) SetOsVersion(v string) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateOsVersion() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateOsVersion()
	})
}

// SetArch sets the "arch" field.
func (u *EndpointUpsertOne) SetArch(v string) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetArch(v)
	})
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateArch() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateArch()
	})
}

// SetClientVersion sets the "client_version" field.
func (u *EndpointUpsertOne) SetClientVersion(v string) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetClientVersion(v)
	})
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateClientVersion() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateClientVersion()
	})
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *EndpointUpsertOne) SetProtocolVersion(v int) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetProtocolVersion(v)
	})
}

// AddProtocolVersion adds v to the "protocol_version" field.
func (u *EndpointUpsertOne) AddProtocolVersion(v int) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.AddProtocolVersion(v)
	})
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateProtocolVersion() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateProtocolVersion()
	})
}

// SetAlias sets the "alias" field.
func (u *EndpointUpsertOne) SetAlias(v string) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetAlias(v)
	})
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateAlias() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateAlias()
	})
}

// ClearAlias clears the value of the "alias" field.
func (u *EndpointUpsertOne) ClearAlias() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.ClearAlias()
	})
}

// SetStatus sets the "status" field.
func (u *EndpointUpsertOne) SetStatus(v endpoint.Status) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateStatus() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *EndpointUpsertOne) SetLastSeenAt(v time.Time) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateLastSeenAt() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *EndpointUpsertOne) ClearLastSeenAt() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EndpointUpsertOne) SetCreatedAt(v time.Time) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateCreatedAt() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EndpointUpsertOne) SetUpdatedAt(v time.Time) *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EndpointUpsertOne) UpdateUpdatedAt() *EndpointUpsertOne {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EndpointUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for EndpointCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EndpointUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EndpointUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: EndpointUpsertOne.ID is not supported by MySQL driver. Use EndpointUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EndpointUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EndpointCreateBulk is the builder for creating many Endpoint entities in bulk.
type EndpointCreateBulk struct {
	config
	err      error
	builders []*EndpointCreate
	conflict []sql.ConflictOption
}

// Save creates the Endpoint entities in the database.
func (_c *EndpointCreateBulk) Save(ctx context.Context) ([]*Endpoint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Endpoint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EndpointMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EndpointCreateBulk) SaveX(ctx context.Context) []*Endpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EndpointCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EndpointCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Endpoint.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EndpointUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *EndpointCreateBulk) OnConflict(opts ...sql.ConflictOption) *EndpointUpsertBulk {
	_c.conflict = opts
	return &EndpointUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Endpoint.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EndpointCreateBulk) OnConflictColumns(columns ...string) *EndpointUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EndpointUpsertBulk{
		create: _c,
	}
}

// EndpointUpsertBulk is the builder for "upsert"-ing
// a bulk of Endpoint nodes.
type EndpointUpsertBulk struct {
	create *EndpointCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Endpoint.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(endpoint.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EndpointUpsertBulk) UpdateNewValues() *EndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(endpoint.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Endpoint.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EndpointUpsertBulk) Ignore() *EndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EndpointUpsertBulk) DoNothing() *EndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EndpointCreateBulk.OnConflict
// documentation for more info.
func (u *EndpointUpsertBulk) Update(set func(*EndpointUpsert)) *EndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EndpointUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *EndpointUpsertBulk) SetUserID(v uuid.UUID) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateUserID() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateUserID()
	})
}

// SetMachineID sets the "machine_id" field.
func (u *EndpointUpsertBulk) SetMachineID(v uuid.UUID) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetMachineID(v)
	})
}

// UpdateMachineID sets the "machine_id" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateMachineID() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateMachineID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *EndpointUpsertBulk) SetDeviceName(v string) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateDeviceName() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateDeviceName()
	})
}

// SetPlatform sets the "platform" field.
func (u *EndpointUpsertBulk) SetPlatform(v endpoint.Platform) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdatePlatform() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdatePlatform()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *EndpointUpsertBulk) SetOsVersion(v string) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateOsVersion() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateOsVersion()
	})
}

// SetArch sets the "arch" field.
func (u *EndpointUpsertBulk) SetArch(v string) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetArch(v)
	})
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateArch() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateArch()
	})
}

// SetClientVersion sets the "client_version" field.
func (u *EndpointUpsertBulk) SetClientVersion(v string) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetClientVersion(v)
	})
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateClientVersion() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateClientVersion()
	})
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *EndpointUpsertBulk) SetProtocolVersion(v int) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetProtocolVersion(v)
	})
}

// AddProtocolVersion adds v to the "protocol_version" field.
func (u *EndpointUpsertBulk) AddProtocolVersion(v int) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.AddProtocolVersion(v)
	})
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateProtocolVersion() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateProtocolVersion()
	})
}

// SetAlias sets the "alias" field.
func (u *EndpointUpsertBulk) SetAlias(v string) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetAlias(v)
	})
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateAlias() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateAlias()
	})
}

// ClearAlias clears the value of the "alias" field.
func (u *EndpointUpsertBulk) ClearAlias() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.ClearAlias()
	})
}

// SetStatus sets the "status" field.
func (u *EndpointUpsertBulk) SetStatus(v endpoint.Status) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateStatus() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *EndpointUpsertBulk) SetLastSeenAt(v time.Time) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateLastSeenAt() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *EndpointUpsertBulk) ClearLastSeenAt() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EndpointUpsertBulk) SetCreatedAt(v time.Time) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateCreatedAt() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EndpointUpsertBulk) SetUpdatedAt(v time.Time) *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EndpointUpsertBulk) UpdateUpdatedAt() *EndpointUpsertBulk {
	return u.Update(func(s *EndpointUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EndpointUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the EndpointCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for EndpointCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EndpointUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
