// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/licenseaudit"
	"github.com/google/uuid"
)

// LicenseAuditCreate is the builder for creating a LicenseAudit entity.
type LicenseAuditCreate struct {
	config
	mutation *LicenseAuditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLicenseID sets the "license_id" field.
func (_c *LicenseAuditCreate) SetLicenseID(v string) *LicenseAuditCreate {
	_c.mutation.SetLicenseID(v)
	return _c
}

// SetNillableLicenseID sets the "license_id" field if the given value is not nil.
func (_c *LicenseAuditCreate) SetNillableLicenseID(v *string) *LicenseAuditCreate {
	if v != nil {
		_c.SetLicenseID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *LicenseAuditCreate) SetAction(v licenseaudit.Action) *LicenseAuditCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *LicenseAuditCreate) SetResult(v licenseaudit.Result) *LicenseAuditCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *LicenseAuditCreate) SetMessage(v string) *LicenseAuditCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *LicenseAuditCreate) SetNillableMessage(v *string) *LicenseAuditCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LicenseAuditCreate) SetCreatedAt(v time.Time) *LicenseAuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LicenseAuditCreate) SetNillableCreatedAt(v *time.Time) *LicenseAuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LicenseAuditCreate) SetID(v uuid.UUID) *LicenseAuditCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LicenseAuditMutation object of the builder.
func (_c *LicenseAuditCreate) Mutation() *LicenseAuditMutation {
	return _c.mutation
}

// Save creates the LicenseAudit in the database.
func (_c *LicenseAuditCreate) Save(ctx context.Context) (*LicenseAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LicenseAuditCreate) SaveX(ctx context.Context) *LicenseAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LicenseAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LicenseAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LicenseAuditCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := licenseaudit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LicenseAuditCreate) check() error {
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`db: missing required field "LicenseAudit.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := licenseaudit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`db: validator failed for field "LicenseAudit.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`db: missing required field "LicenseAudit.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := licenseaudit.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`db: validator failed for field "LicenseAudit.result": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "LicenseAudit.created_at"`)}
	}
	return nil
}

func (_c *LicenseAuditCreate) sqlSave(ctx context.Context) (*LicenseAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LicenseAuditCreate) createSpec() (*LicenseAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &LicenseAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(licenseaudit.Table, sqlgraph.NewFieldSpec(licenseaudit.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.LicenseID(); ok {
		_spec.SetField(licenseaudit.FieldLicenseID, field.TypeString, value)
		_node.LicenseID = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(licenseaudit.FieldAction, field.TypeEnum, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(licenseaudit.FieldResult, field.TypeEnum, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(licenseaudit.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(licenseaudit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LicenseAudit.Create().
//		SetLicenseID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LicenseAuditUpsert) {
//			SetLicenseID(v+v).
//		}).
//		Exec(ctx)
func (_c *LicenseAuditCreate) OnConflict(opts ...sql.ConflictOption) *LicenseAuditUpsertOne {
	_c.conflict = opts
	return &LicenseAuditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LicenseAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LicenseAuditCreate) OnConflictColumns(columns ...string) *LicenseAuditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LicenseAuditUpsertOne{
		create: _c,
	}
}

type (
	// LicenseAuditUpsertOne is the builder for "upsert"-ing
	//  one LicenseAudit node.
	LicenseAuditUpsertOne struct {
		create *LicenseAuditCreate
	}

	// LicenseAuditUpsert is the "OnConflict" setter.
	LicenseAuditUpsert struct {
		*sql.UpdateSet
	}
)

// SetLicenseID sets the "license_id" field.
func (u *LicenseAuditUpsert) SetLicenseID(v string) *LicenseAuditUpsert {
	u.Set(licenseaudit.FieldLicenseID, v)
	return u
}

// UpdateLicenseID sets the "license_id" field to the value that was provided on create.
func (u *LicenseAuditUpsert) UpdateLicenseID() *LicenseAuditUpsert {
	u.SetExcluded(licenseaudit.FieldLicenseID)
	return u
}

// ClearLicenseID clears the value of the "license_id" field.
func (u *LicenseAuditUpsert) ClearLicenseID() *LicenseAuditUpsert {
	u.SetNull(licenseaudit.FieldLicenseID)
	return u
}

// SetAction sets the "action" field.
func (u *LicenseAuditUpsert) SetAction(v licenseaudit.Action) *LicenseAuditUpsert {
	u.Set(licenseaudit.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *LicenseAuditUpsert) UpdateAction() *LicenseAuditUpsert {
	u.SetExcluded(licenseaudit.FieldAction)
	return u
}

// SetResult sets the "result" field.
func (u *LicenseAuditUpsert) SetResult(v licenseaudit.Result) *LicenseAuditUpsert {
	u.Set(licenseaudit.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *LicenseAuditUpsert) UpdateResult() *LicenseAuditUpsert {
	u.SetExcluded(licenseaudit.FieldResult)
	return u
}

// SetMessage sets the "message" field.
func (u *LicenseAuditUpsert) SetMessage(v string) *LicenseAuditUpsert {
	u.Set(licenseaudit.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *LicenseAuditUpsert) UpdateMessage() *LicenseAuditUpsert {
	u.SetExcluded(licenseaudit.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *LicenseAuditUpsert) ClearMessage() *LicenseAuditUpsert {
	u.SetNull(licenseaudit.FieldMessage)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LicenseAuditUpsert) SetCreatedAt(v time.Time) *LicenseAuditUpsert {
	u.Set(licenseaudit.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LicenseAuditUpsert) UpdateCreatedAt() *LicenseAuditUpsert {
	u.SetExcluded(licenseaudit.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LicenseAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(licenseaudit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LicenseAuditUpsertOne) UpdateNewValues() *LicenseAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(licenseaudit.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LicenseAudit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LicenseAuditUpsertOne) Ignore() *LicenseAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LicenseAuditUpsertOne) DoNothing() *LicenseAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LicenseAuditCreate.OnConflict
// documentation for more info.
func (u *LicenseAuditUpsertOne) Update(set func(*LicenseAuditUpsert)) *LicenseAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LicenseAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetLicenseID sets the "license_id" field.
func (u *LicenseAuditUpsertOne) SetLicenseID(v string) *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetLicenseID(v)
	})
}

// UpdateLicenseID sets the "license_id" field to the value that was provided on create.
func (u *LicenseAuditUpsertOne) UpdateLicenseID() *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateLicenseID()
	})
}

// ClearLicenseID clears the value of the "license_id" field.
func (u *LicenseAuditUpsertOne) ClearLicenseID() *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.ClearLicenseID()
	})
}

// SetAction sets the "action" field.
func (u *LicenseAuditUpsertOne) SetAction(v licenseaudit.Action) *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *LicenseAuditUpsertOne) UpdateAction() *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateAction()
	})
}

// SetResult sets the "result" field.
func (u *LicenseAuditUpsertOne) SetResult(v licenseaudit.Result) *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *LicenseAuditUpsertOne) UpdateResult() *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateResult()
	})
}

// SetMessage sets the "message" field.
func (u *LicenseAuditUpsertOne) SetMessage(v string) *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *LicenseAuditUpsertOne) UpdateMessage() *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *LicenseAuditUpsertOne) ClearMessage() *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.ClearMessage()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LicenseAuditUpsertOne) SetCreatedAt(v time.Time) *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LicenseAuditUpsertOne) UpdateCreatedAt() *LicenseAuditUpsertOne {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *LicenseAuditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for LicenseAuditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LicenseAuditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LicenseAuditUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: LicenseAuditUpsertOne.ID is not supported by MySQL driver. Use LicenseAuditUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LicenseAuditUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LicenseAuditCreateBulk is the builder for creating many LicenseAudit entities in bulk.
type LicenseAuditCreateBulk struct {
	config
	err      error
	builders []*LicenseAuditCreate
	conflict []sql.ConflictOption
}

// Save creates the LicenseAudit entities in the database.
func (_c *LicenseAuditCreateBulk) Save(ctx context.Context) ([]*LicenseAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LicenseAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LicenseAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LicenseAuditCreateBulk) SaveX(ctx context.Context) []*LicenseAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LicenseAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LicenseAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LicenseAudit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LicenseAuditUpsert) {
//			SetLicenseID(v+v).
//		}).
//		Exec(ctx)
func (_c *LicenseAuditCreateBulk) OnConflict(opts ...sql.ConflictOption) *LicenseAuditUpsertBulk {
	_c.conflict = opts
	return &LicenseAuditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LicenseAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LicenseAuditCreateBulk) OnConflictColumns(columns ...string) *LicenseAuditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LicenseAuditUpsertBulk{
		create: _c,
	}
}

// LicenseAuditUpsertBulk is the builder for "upsert"-ing
// a bulk of LicenseAudit nodes.
type LicenseAuditUpsertBulk struct {
	create *LicenseAuditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LicenseAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(licenseaudit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LicenseAuditUpsertBulk) UpdateNewValues() *LicenseAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(licenseaudit.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LicenseAudit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LicenseAuditUpsertBulk) Ignore() *LicenseAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LicenseAuditUpsertBulk) DoNothing() *LicenseAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LicenseAuditCreateBulk.OnConflict
// documentation for more info.
func (u *LicenseAuditUpsertBulk) Update(set func(*LicenseAuditUpsert)) *LicenseAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LicenseAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetLicenseID sets the "license_id" field.
func (u *LicenseAuditUpsertBulk) SetLicenseID(v string) *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetLicenseID(v)
	})
}

// UpdateLicenseID sets the "license_id" field to the value that was provided on create.
func (u *LicenseAuditUpsertBulk) UpdateLicenseID() *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateLicenseID()
	})
}

// ClearLicenseID clears the value of the "license_id" field.
func (u *LicenseAuditUpsertBulk) ClearLicenseID() *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.ClearLicenseID()
	})
}

// SetAction sets the "action" field.
func (u *LicenseAuditUpsertBulk) SetAction(v licenseaudit.Action) *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *LicenseAuditUpsertBulk) UpdateAction() *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateAction()
	})
}

// SetResult sets the "result" field.
func (u *LicenseAuditUpsertBulk) SetResult(v licenseaudit.Result) *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *LicenseAuditUpsertBulk) UpdateResult() *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateResult()
	})
}

// SetMessage sets the "message" field.
func (u *LicenseAuditUpsertBulk) SetMessage(v string) *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *LicenseAuditUpsertBulk) UpdateMessage() *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *LicenseAuditUpsertBulk) ClearMessage() *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.ClearMessage()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LicenseAuditUpsertBulk) SetCreatedAt(v time.Time) *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LicenseAuditUpsertBulk) UpdateCreatedAt() *LicenseAuditUpsertBulk {
	return u.Update(func(s *LicenseAuditUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *LicenseAuditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the LicenseAuditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for LicenseAuditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LicenseAuditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
