// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/licenseaudit"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
)

// LicenseAuditDelete is the builder for deleting a LicenseAudit entity.
type LicenseAuditDelete struct {
	config
	hooks    []Hook
	mutation *LicenseAuditMutation
}

// Where appends a list predicates to the LicenseAuditDelete builder.
func (_d *LicenseAuditDelete) Where(ps ...predicate.LicenseAudit) *LicenseAuditDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LicenseAuditDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LicenseAuditDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LicenseAuditDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(licenseaudit.Table, sqlgraph.NewFieldSpec(licenseaudit.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LicenseAuditDeleteOne is the builder for deleting a single LicenseAudit entity.
type LicenseAuditDeleteOne struct {
	_d *LicenseAuditDelete
}

// Where appends a list predicates to the LicenseAuditDelete builder.
func (_d *LicenseAuditDeleteOne) Where(ps ...predicate.LicenseAudit) *LicenseAuditDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LicenseAuditDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{licenseaudit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LicenseAuditDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
