// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/licenseinstallation"
	"github.com/google/uuid"
)

// LicenseInstallationCreate is the builder for creating a LicenseInstallation entity.
type LicenseInstallationCreate struct {
	config
	mutation *LicenseInstallationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInstallationID sets the "installation_id" field.
func (_c *LicenseInstallationCreate) SetInstallationID(v string) *LicenseInstallationCreate {
	_c.mutation.SetInstallationID(v)
	return _c
}

// SetProduct sets the "product" field.
func (_c *LicenseInstallationCreate) SetProduct(v licenseinstallation.Product) *LicenseInstallationCreate {
	_c.mutation.SetProduct(v)
	return _c
}

// SetProductVersion sets the "product_version" field.
func (_c *LicenseInstallationCreate) SetProductVersion(v string) *LicenseInstallationCreate {
	_c.mutation.SetProductVersion(v)
	return _c
}

// SetNillableProductVersion sets the "product_version" field if the given value is not nil.
func (_c *LicenseInstallationCreate) SetNillableProductVersion(v *string) *LicenseInstallationCreate {
	if v != nil {
		_c.SetProductVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LicenseInstallationCreate) SetCreatedAt(v time.Time) *LicenseInstallationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LicenseInstallationCreate) SetNillableCreatedAt(v *time.Time) *LicenseInstallationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LicenseInstallationCreate) SetUpdatedAt(v time.Time) *LicenseInstallationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LicenseInstallationCreate) SetNillableUpdatedAt(v *time.Time) *LicenseInstallationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LicenseInstallationCreate) SetID(v uuid.UUID) *LicenseInstallationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LicenseInstallationMutation object of the builder.
func (_c *LicenseInstallationCreate) Mutation() *LicenseInstallationMutation {
	return _c.mutation
}

// Save creates the LicenseInstallation in the database.
func (_c *LicenseInstallationCreate) Save(ctx context.Context) (*LicenseInstallation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LicenseInstallationCreate) SaveX(ctx context.Context) *LicenseInstallation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LicenseInstallationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LicenseInstallationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LicenseInstallationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := licenseinstallation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := licenseinstallation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LicenseInstallationCreate) check() error {
	if _, ok := _c.mutation.InstallationID(); !ok {
		return &ValidationError{Name: "installation_id", err: errors.New(`db: missing required field "LicenseInstallation.installation_id"`)}
	}
	if v, ok := _c.mutation.InstallationID(); ok {
		if err := licenseinstallation.InstallationIDValidator(v); err != nil {
			return &ValidationError{Name: "installation_id", err: fmt.Errorf(`db: validator failed for field "LicenseInstallation.installation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Product(); !ok {
		return &ValidationError{Name: "product", err: errors.New(`db: missing required field "LicenseInstallation.product"`)}
	}
	if v, ok := _c.mutation.Product(); ok {
		if err := licenseinstallation.ProductValidator(v); err != nil {
			return &ValidationError{Name: "product", err: fmt.Errorf(`db: validator failed for field "LicenseInstallation.product": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "LicenseInstallation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "LicenseInstallation.updated_at"`)}
	}
	return nil
}

func (_c *LicenseInstallationCreate) sqlSave(ctx context.Context) (*LicenseInstallation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LicenseInstallationCreate) createSpec() (*LicenseInstallation, *sqlgraph.CreateSpec) {
	var (
		_node = &LicenseInstallation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(licenseinstallation.Table, sqlgraph.NewFieldSpec(licenseinstallation.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.InstallationID(); ok {
		_spec.SetField(licenseinstallation.FieldInstallationID, field.TypeString, value)
		_node.InstallationID = value
	}
	if value, ok := _c.mutation.Product(); ok {
		_spec.SetField(licenseinstallation.FieldProduct, field.TypeEnum, value)
		_node.Product = value
	}
	if value, ok := _c.mutation.ProductVersion(); ok {
		_spec.SetField(licenseinstallation.FieldProductVersion, field.TypeString, value)
		_node.ProductVersion = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(licenseinstallation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(licenseinstallation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LicenseInstallation.Create().
//		SetInstallationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LicenseInstallationUpsert) {
//			SetInstallationID(v+v).
//		}).
//		Exec(ctx)
func (_c *LicenseInstallationCreate) OnConflict(opts ...sql.ConflictOption) *LicenseInstallationUpsertOne {
	_c.conflict = opts
	return &LicenseInstallationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LicenseInstallation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LicenseInstallationCreate) OnConflictColumns(columns ...string) *LicenseInstallationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LicenseInstallationUpsertOne{
		create: _c,
	}
}

type (
	// LicenseInstallationUpsertOne is the builder for "upsert"-ing
	//  one LicenseInstallation node.
	LicenseInstallationUpsertOne struct {
		create *LicenseInstallationCreate
	}

	// LicenseInstallationUpsert is the "OnConflict" setter.
	LicenseInstallationUpsert struct {
		*sql.UpdateSet
	}
)

// SetInstallationID sets the "installation_id" field.
func (u *LicenseInstallationUpsert) SetInstallationID(v string) *LicenseInstallationUpsert {
	u.Set(licenseinstallation.FieldInstallationID, v)
	return u
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *LicenseInstallationUpsert) UpdateInstallationID() *LicenseInstallationUpsert {
	u.SetExcluded(licenseinstallation.FieldInstallationID)
	return u
}

// SetProduct sets the "product" field.
func (u *LicenseInstallationUpsert) SetProduct(v licenseinstallation.Product) *LicenseInstallationUpsert {
	u.Set(licenseinstallation.FieldProduct, v)
	return u
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *LicenseInstallationUpsert) UpdateProduct() *LicenseInstallationUpsert {
	u.SetExcluded(licenseinstallation.FieldProduct)
	return u
}

// SetProductVersion sets the "product_version" field.
func (u *LicenseInstallationUpsert) SetProductVersion(v string) *LicenseInstallationUpsert {
	u.Set(licenseinstallation.FieldProductVersion, v)
	return u
}

// UpdateProductVersion sets the "product_version" field to the value that was provided on create.
func (u *LicenseInstallationUpsert) UpdateProductVersion() *LicenseInstallationUpsert {
	u.SetExcluded(licenseinstallation.FieldProductVersion)
	return u
}

// ClearProductVersion clears the value of the "product_version" field.
func (u *LicenseInstallationUpsert) ClearProductVersion() *LicenseInstallationUpsert {
	u.SetNull(licenseinstallation.FieldProductVersion)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LicenseInstallationUpsert) SetCreatedAt(v time.Time) *LicenseInstallationUpsert {
	u.Set(licenseinstallation.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LicenseInstallationUpsert) UpdateCreatedAt() *LicenseInstallationUpsert {
	u.SetExcluded(licenseinstallation.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LicenseInstallationUpsert) SetUpdatedAt(v time.Time) *LicenseInstallationUpsert {
	u.Set(licenseinstallation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LicenseInstallationUpsert) UpdateUpdatedAt() *LicenseInstallationUpsert {
	u.SetExcluded(licenseinstallation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LicenseInstallation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(licenseinstallation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LicenseInstallationUpsertOne) UpdateNewValues() *LicenseInstallationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(licenseinstallation.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LicenseInstallation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LicenseInstallationUpsertOne) Ignore() *LicenseInstallationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LicenseInstallationUpsertOne) DoNothing() *LicenseInstallationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LicenseInstallationCreate.OnConflict
// documentation for more info.
func (u *LicenseInstallationUpsertOne) Update(set func(*LicenseInstallationUpsert)) *LicenseInstallationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LicenseInstallationUpsert{UpdateSet: update})
	}))
	return u
}

// SetInstallationID sets the "installation_id" field.
func (u *LicenseInstallationUpsertOne) SetInstallationID(v string) *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetInstallationID(v)
	})
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *LicenseInstallationUpsertOne) UpdateInstallationID() *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateInstallationID()
	})
}

// SetProduct sets the "product" field.
func (u *LicenseInstallationUpsertOne) SetProduct(v licenseinstallation.Product) *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *LicenseInstallationUpsertOne) UpdateProduct() *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateProduct()
	})
}

// SetProductVersion sets the "product_version" field.
func (u *LicenseInstallationUpsertOne) SetProductVersion(v string) *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetProductVersion(v)
	})
}

// UpdateProductVersion sets the "product_version" field to the value that was provided on create.
func (u *LicenseInstallationUpsertOne) UpdateProductVersion() *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateProductVersion()
	})
}

// ClearProductVersion clears the value of the "product_version" field.
func (u *LicenseInstallationUpsertOne) ClearProductVersion() *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.ClearProductVersion()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LicenseInstallationUpsertOne) SetCreatedAt(v time.Time) *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LicenseInstallationUpsertOne) UpdateCreatedAt() *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LicenseInstallationUpsertOne) SetUpdatedAt(v time.Time) *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LicenseInstallationUpsertOne) UpdateUpdatedAt() *LicenseInstallationUpsertOne {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LicenseInstallationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for LicenseInstallationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LicenseInstallationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LicenseInstallationUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: LicenseInstallationUpsertOne.ID is not supported by MySQL driver. Use LicenseInstallationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LicenseInstallationUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LicenseInstallationCreateBulk is the builder for creating many LicenseInstallation entities in bulk.
type LicenseInstallationCreateBulk struct {
	config
	err      error
	builders []*LicenseInstallationCreate
	conflict []sql.ConflictOption
}

// Save creates the LicenseInstallation entities in the database.
func (_c *LicenseInstallationCreateBulk) Save(ctx context.Context) ([]*LicenseInstallation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LicenseInstallation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LicenseInstallationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LicenseInstallationCreateBulk) SaveX(ctx context.Context) []*LicenseInstallation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LicenseInstallationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LicenseInstallationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LicenseInstallation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LicenseInstallationUpsert) {
//			SetInstallationID(v+v).
//		}).
//		Exec(ctx)
func (_c *LicenseInstallationCreateBulk) OnConflict(opts ...sql.ConflictOption) *LicenseInstallationUpsertBulk {
	_c.conflict = opts
	return &LicenseInstallationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LicenseInstallation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LicenseInstallationCreateBulk) OnConflictColumns(columns ...string) *LicenseInstallationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LicenseInstallationUpsertBulk{
		create: _c,
	}
}

// LicenseInstallationUpsertBulk is the builder for "upsert"-ing
// a bulk of LicenseInstallation nodes.
type LicenseInstallationUpsertBulk struct {
	create *LicenseInstallationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LicenseInstallation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(licenseinstallation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LicenseInstallationUpsertBulk) UpdateNewValues() *LicenseInstallationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(licenseinstallation.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LicenseInstallation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LicenseInstallationUpsertBulk) Ignore() *LicenseInstallationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LicenseInstallationUpsertBulk) DoNothing() *LicenseInstallationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LicenseInstallationCreateBulk.OnConflict
// documentation for more info.
func (u *LicenseInstallationUpsertBulk) Update(set func(*LicenseInstallationUpsert)) *LicenseInstallationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LicenseInstallationUpsert{UpdateSet: update})
	}))
	return u
}

// SetInstallationID sets the "installation_id" field.
func (u *LicenseInstallationUpsertBulk) SetInstallationID(v string) *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetInstallationID(v)
	})
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *LicenseInstallationUpsertBulk) UpdateInstallationID() *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateInstallationID()
	})
}

// SetProduct sets the "product" field.
func (u *LicenseInstallationUpsertBulk) SetProduct(v licenseinstallation.Product) *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *LicenseInstallationUpsertBulk) UpdateProduct() *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateProduct()
	})
}

// SetProductVersion sets the "product_version" field.
func (u *LicenseInstallationUpsertBulk) SetProductVersion(v string) *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetProductVersion(v)
	})
}

// UpdateProductVersion sets the "product_version" field to the value that was provided on create.
func (u *LicenseInstallationUpsertBulk) UpdateProductVersion() *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateProductVersion()
	})
}

// ClearProductVersion clears the value of the "product_version" field.
func (u *LicenseInstallationUpsertBulk) ClearProductVersion() *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.ClearProductVersion()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LicenseInstallationUpsertBulk) SetCreatedAt(v time.Time) *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LicenseInstallationUpsertBulk) UpdateCreatedAt() *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LicenseInstallationUpsertBulk) SetUpdatedAt(v time.Time) *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LicenseInstallationUpsertBulk) UpdateUpdatedAt() *LicenseInstallationUpsertBulk {
	return u.Update(func(s *LicenseInstallationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LicenseInstallationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the LicenseInstallationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for LicenseInstallationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LicenseInstallationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
