// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/chaitin/MonkeyCode/backend/db/licenseaudit"
	"github.com/google/uuid"
)

// LicenseAudit is the model entity for the LicenseAudit schema.
type LicenseAudit struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// LicenseID holds the value of the "license_id" field.
	LicenseID string `json:"license_id,omitempty"`
	// Action holds the value of the "action" field.
	Action licenseaudit.Action `json:"action,omitempty"`
	// Result holds the value of the "result" field.
	Result licenseaudit.Result `json:"result,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LicenseAudit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case licenseaudit.FieldLicenseID, licenseaudit.FieldAction, licenseaudit.FieldResult, licenseaudit.FieldMessage:
			values[i] = new(sql.NullString)
		case licenseaudit.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case licenseaudit.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LicenseAudit fields.
func (_m *LicenseAudit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case licenseaudit.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case licenseaudit.FieldLicenseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license_id", values[i])
			} else if value.Valid {
				_m.LicenseID = value.String
			}
		case licenseaudit.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = licenseaudit.Action(value.String)
			}
		case licenseaudit.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = licenseaudit.Result(value.String)
			}
		case licenseaudit.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case licenseaudit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LicenseAudit.
// This includes values selected through modifiers, order, etc.
func (_m *LicenseAudit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LicenseAudit.
// Note that you need to call LicenseAudit.Unwrap() before calling this method if this LicenseAudit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LicenseAudit) Update() *LicenseAuditUpdateOne {
	return NewLicenseAuditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LicenseAudit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LicenseAudit) Unwrap() *LicenseAudit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: LicenseAudit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LicenseAudit) String() string {
	var builder strings.Builder
	builder.WriteString("LicenseAudit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("license_id=")
	builder.WriteString(_m.LicenseID)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(fmt.Sprintf("%v", _m.Result))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LicenseAudits is a parsable slice of LicenseAudit.
type LicenseAudits []*LicenseAudit
