// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/licenseaudit"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
)

// LicenseAuditUpdate is the builder for updating LicenseAudit entities.
type LicenseAuditUpdate struct {
	config
	hooks     []Hook
	mutation  *LicenseAuditMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LicenseAuditUpdate builder.
func (_u *LicenseAuditUpdate) Where(ps ...predicate.LicenseAudit) *LicenseAuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLicenseID sets the "license_id" field.
func (_u *LicenseAuditUpdate) SetLicenseID(v string) *LicenseAuditUpdate {
	_u.mutation.SetLicenseID(v)
	return _u
}

// SetNillableLicenseID sets the "license_id" field if the given value is not nil.
func (_u *LicenseAuditUpdate) SetNillableLicenseID(v *string) *LicenseAuditUpdate {
	if v != nil {
		_u.SetLicenseID(*v)
	}
	return _u
}

// ClearLicenseID clears the value of the "license_id" field.
func (_u *LicenseAuditUpdate) ClearLicenseID() *LicenseAuditUpdate {
	_u.mutation.ClearLicenseID()
	return _u
}

// SetAction sets the "action" field.
func (_u *LicenseAuditUpdate) SetAction(v licenseaudit.Action) *LicenseAuditUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *LicenseAuditUpdate) SetNillableAction(v *licenseaudit.Action) *LicenseAuditUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *LicenseAuditUpdate) SetResult(v licenseaudit.Result) *LicenseAuditUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *LicenseAuditUpdate) SetNillableResult(v *licenseaudit.Result) *LicenseAuditUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *LicenseAuditUpdate) SetMessage(v string) *LicenseAuditUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *LicenseAuditUpdate) SetNillableMessage(v *string) *LicenseAuditUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *LicenseAuditUpdate) ClearMessage() *LicenseAuditUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LicenseAuditUpdate) SetCreatedAt(v time.Time) *LicenseAuditUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LicenseAuditUpdate) SetNillableCreatedAt(v *time.Time) *LicenseAuditUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the LicenseAuditMutation object of the builder.
func (_u *LicenseAuditUpdate) Mutation() *LicenseAuditMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LicenseAuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LicenseAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LicenseAuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LicenseAuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LicenseAuditUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := licenseaudit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`db: validator failed for field "LicenseAudit.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := licenseaudit.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`db: validator failed for field "LicenseAudit.result": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LicenseAuditUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LicenseAuditUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LicenseAuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(licenseaudit.Table, licenseaudit.Columns, sqlgraph.NewFieldSpec(licenseaudit.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LicenseID(); ok {
		_spec.SetField(licenseaudit.FieldLicenseID, field.TypeString, value)
	}
	if _u.mutation.LicenseIDCleared() {
		_spec.ClearField(licenseaudit.FieldLicenseID, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(licenseaudit.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(licenseaudit.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(licenseaudit.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(licenseaudit.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(licenseaudit.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{licenseaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LicenseAuditUpdateOne is the builder for updating a single LicenseAudit entity.
type LicenseAuditUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LicenseAuditMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetLicenseID sets the "license_id" field.
func (_u *LicenseAuditUpdateOne) SetLicenseID(v string) *LicenseAuditUpdateOne {
	_u.mutation.SetLicenseID(v)
	return _u
}

// SetNillableLicenseID sets the "license_id" field if the given value is not nil.
func (_u *LicenseAuditUpdateOne) SetNillableLicenseID(v *string) *LicenseAuditUpdateOne {
	if v != nil {
		_u.SetLicenseID(*v)
	}
	return _u
}

// ClearLicenseID clears the value of the "license_id" field.
func (_u *LicenseAuditUpdateOne) ClearLicenseID() *LicenseAuditUpdateOne {
	_u.mutation.ClearLicenseID()
	return _u
}

// SetAction sets the "action" field.
func (_u *LicenseAuditUpdateOne) SetAction(v licenseaudit.Action) *LicenseAuditUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *LicenseAuditUpdateOne) SetNillableAction(v *licenseaudit.Action) *LicenseAuditUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *LicenseAuditUpdateOne) SetResult(v licenseaudit.Result) *LicenseAuditUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *LicenseAuditUpdateOne) SetNillableResult(v *licenseaudit.Result) *LicenseAuditUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *LicenseAuditUpdateOne) SetMessage(v string) *LicenseAuditUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *LicenseAuditUpdateOne) SetNillableMessage(v *string) *LicenseAuditUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *LicenseAuditUpdateOne) ClearMessage() *LicenseAuditUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LicenseAuditUpdateOne) SetCreatedAt(v time.Time) *LicenseAuditUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LicenseAuditUpdateOne) SetNillableCreatedAt(v *time.Time) *LicenseAuditUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the LicenseAuditMutation object of the builder.
func (_u *LicenseAuditUpdateOne) Mutation() *LicenseAuditMutation {
	return _u.mutation
}

// Where appends a list predicates to the LicenseAuditUpdate builder.
func (_u *LicenseAuditUpdateOne) Where(ps ...predicate.LicenseAudit) *LicenseAuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LicenseAuditUpdateOne) Select(field string, fields ...string) *LicenseAuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LicenseAudit entity.
func (_u *LicenseAuditUpdateOne) Save(ctx context.Context) (*LicenseAudit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LicenseAuditUpdateOne) SaveX(ctx context.Context) *LicenseAudit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LicenseAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LicenseAuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LicenseAuditUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := licenseaudit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`db: validator failed for field "LicenseAudit.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := licenseaudit.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`db: validator failed for field "LicenseAudit.result": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LicenseAuditUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LicenseAuditUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LicenseAuditUpdateOne) sqlSave(ctx context.Context) (_node *LicenseAudit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(licenseaudit.Table, licenseaudit.Columns, sqlgraph.NewFieldSpec(licenseaudit.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "LicenseAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, licenseaudit.FieldID)
		for _, f := range fields {
			if !licenseaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != licenseaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LicenseID(); ok {
		_spec.SetField(licenseaudit.FieldLicenseID, field.TypeString, value)
	}
	if _u.mutation.LicenseIDCleared() {
		_spec.ClearField(licenseaudit.FieldLicenseID, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(licenseaudit.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(licenseaudit.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(licenseaudit.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(licenseaudit.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(licenseaudit.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &LicenseAudit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{licenseaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
