// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/chaitin/MonkeyCode/backend/db/licenserecord"
	"github.com/google/uuid"
)

// LicenseRecord is the model entity for the LicenseRecord schema.
type LicenseRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// LicenseID holds the value of the "license_id" field.
	LicenseID string `json:"license_id,omitempty"`
	// InstallationID holds the value of the "installation_id" field.
	InstallationID string `json:"installation_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// CustomerName holds the value of the "customer_name" field.
	CustomerName string `json:"customer_name,omitempty"`
	// Seats holds the value of the "seats" field.
	Seats int `json:"seats,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt time.Time `json:"issued_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// PayloadJSON holds the value of the "payload_json" field.
	PayloadJSON string `json:"payload_json,omitempty"`
	// Signature holds the value of the "signature" field.
	Signature string `json:"signature,omitempty"`
	// KeyID holds the value of the "key_id" field.
	KeyID string `json:"key_id,omitempty"`
	// Alg holds the value of the "alg" field.
	Alg licenserecord.Alg `json:"alg,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// ImportedAt holds the value of the "imported_at" field.
	ImportedAt time.Time `json:"imported_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LicenseRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case licenserecord.FieldActive:
			values[i] = new(sql.NullBool)
		case licenserecord.FieldSeats:
			values[i] = new(sql.NullInt64)
		case licenserecord.FieldLicenseID, licenserecord.FieldInstallationID, licenserecord.FieldCustomerID, licenserecord.FieldCustomerName, licenserecord.FieldPayloadJSON, licenserecord.FieldSignature, licenserecord.FieldKeyID, licenserecord.FieldAlg:
			values[i] = new(sql.NullString)
		case licenserecord.FieldIssuedAt, licenserecord.FieldExpiresAt, licenserecord.FieldImportedAt, licenserecord.FieldCreatedAt, licenserecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case licenserecord.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LicenseRecord fields.
func (_m *LicenseRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case licenserecord.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case licenserecord.FieldLicenseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license_id", values[i])
			} else if value.Valid {
				_m.LicenseID = value.String
			}
		case licenserecord.FieldInstallationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field installation_id", values[i])
			} else if value.Valid {
				_m.InstallationID = value.String
			}
		case licenserecord.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				_m.CustomerID = value.String
			}
		case licenserecord.FieldCustomerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_name", values[i])
			} else if value.Valid {
				_m.CustomerName = value.String
			}
		case licenserecord.FieldSeats:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seats", values[i])
			} else if value.Valid {
				_m.Seats = int(value.Int64)
			}
		case licenserecord.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = value.Time
			}
		case licenserecord.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case licenserecord.FieldPayloadJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_json", values[i])
			} else if value.Valid {
				_m.PayloadJSON = value.String
			}
		case licenserecord.FieldSignature:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signature", values[i])
			} else if value.Valid {
				_m.Signature = value.String
			}
		case licenserecord.FieldKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_id", values[i])
			} else if value.Valid {
				_m.KeyID = value.String
			}
		case licenserecord.FieldAlg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alg", values[i])
			} else if value.Valid {
				_m.Alg = licenserecord.Alg(value.String)
			}
		case licenserecord.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case licenserecord.FieldImportedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field imported_at", values[i])
			} else if value.Valid {
				_m.ImportedAt = value.Time
			}
		case licenserecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case licenserecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LicenseRecord.
// This includes values selected through modifiers, order, etc.
func (_m *LicenseRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LicenseRecord.
// Note that you need to call LicenseRecord.Unwrap() before calling this method if this LicenseRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LicenseRecord) Update() *LicenseRecordUpdateOne {
	return NewLicenseRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LicenseRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LicenseRecord) Unwrap() *LicenseRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: LicenseRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LicenseRecord) String() string {
	var builder strings.Builder
	builder.WriteString("LicenseRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("license_id=")
	builder.WriteString(_m.LicenseID)
	builder.WriteString(", ")
	builder.WriteString("installation_id=")
	builder.WriteString(_m.InstallationID)
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(_m.CustomerID)
	builder.WriteString(", ")
	builder.WriteString("customer_name=")
	builder.WriteString(_m.CustomerName)
	builder.WriteString(", ")
	builder.WriteString("seats=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seats))
	builder.WriteString(", ")
	builder.WriteString("issued_at=")
	builder.WriteString(_m.IssuedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("payload_json=")
	builder.WriteString(_m.PayloadJSON)
	builder.WriteString(", ")
	builder.WriteString("signature=")
	builder.WriteString(_m.Signature)
	builder.WriteString(", ")
	builder.WriteString("key_id=")
	builder.WriteString(_m.KeyID)
	builder.WriteString(", ")
	builder.WriteString("alg=")
	builder.WriteString(fmt.Sprintf("%v", _m.Alg))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("imported_at=")
	builder.WriteString(_m.ImportedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LicenseRecords is a parsable slice of LicenseRecord.
type LicenseRecords []*LicenseRecord
