// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const clearImportExpertConnectors = `-- name: ClearImportExpertConnectors :exec
DELETE FROM expert_connectors WHERE expert_id=$1::uuid
`

func (q *Queries) ClearImportExpertConnectors(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, clearImportExpertConnectors, dollar_1)
	return err
}

const clearImportExpertRules = `-- name: ClearImportExpertRules :exec
DELETE FROM expert_rules WHERE expert_id=$1::uuid
`

func (q *Queries) ClearImportExpertRules(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, clearImportExpertRules, dollar_1)
	return err
}

const clearImportExpertSkills = `-- name: ClearImportExpertSkills :exec
DELETE FROM expert_skills WHERE expert_id=$1::uuid
`

func (q *Queries) ClearImportExpertSkills(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, clearImportExpertSkills, dollar_1)
	return err
}

const createImportBatch = `-- name: CreateImportBatch :exec
INSERT INTO resource_imports (id,publisher,release_id,version,manifest_sha256,actor_user_id,status,result_counts)
VALUES (($1::jsonb->>'id')::uuid,$1::jsonb->>'publisher',
        ($1::jsonb->>'release_id')::uuid,($1::jsonb->>'version')::bigint,
        $1::jsonb->>'manifest_sha256',($1::jsonb->>'actor_user_id')::uuid,
        'succeeded',$1::jsonb->'result_counts')
`

func (q *Queries) CreateImportBatch(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, createImportBatch, data)
	return err
}

const createImportConnector = `-- name: CreateImportConnector :exec
INSERT INTO connectors (id,owner_user_id,ownership_type,name,description,url,
                        authorization_mode,authorization_method,oauth_config,timeout_ms,auth_header_name,name_i18n,description_i18n)
SELECT (d->>'id')::uuid,(d->>'actor_id')::uuid,'system',d->>'name','',d->>'url',d->>'authorization_mode',
       NULLIF(d->>'authorization_method',''),d->'oauth_config',(d->>'timeout_ms')::int,d->>'auth_header_name',d->'name_i18n',d->'description_i18n'
FROM (SELECT $1::jsonb AS d) input
`

func (q *Queries) CreateImportConnector(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, createImportConnector, data)
	return err
}

const createImportExpert = `-- name: CreateImportExpert :exec
INSERT INTO experts (id,created_by_user_id,owner_user_id,ownership_type,name,description,prompt,
                     avatar_s3_key,name_i18n,description_i18n)
SELECT (d->>'id')::uuid,(d->>'actor_id')::uuid,(d->>'actor_id')::uuid,'system',d->>'name',d->>'description',d->>'prompt',
       d->>'avatar_s3_key',d->'name_i18n',d->'description_i18n'
FROM (SELECT $1::jsonb AS d) input
`

func (q *Queries) CreateImportExpert(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, createImportExpert, data)
	return err
}

const createImportRule = `-- name: CreateImportRule :exec
INSERT INTO rules (id,owner_user_id,ownership_type,name,content,name_i18n,description_i18n)
SELECT (d->>'id')::uuid,(d->>'actor_id')::uuid,'system',d->>'name',d->>'content',d->'name_i18n',d->'description_i18n'
FROM (SELECT $1::jsonb AS d) input
`

func (q *Queries) CreateImportRule(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, createImportRule, data)
	return err
}

const createImportSkill = `-- name: CreateImportSkill :exec
INSERT INTO skills (id,owner_user_id,ownership_type,name,description,name_i18n,description_i18n,
                    package_file_name,package_s3_key,package_size_bytes,package_sha256,file_count)
SELECT (d->>'id')::uuid,(d->>'actor_id')::uuid,'system',d->>'name',d->>'description',d->'name_i18n',d->'description_i18n',
       d->>'package_file_name',d->>'package_s3_key',(d->>'package_size_bytes')::bigint,d->>'package_sha256',(d->>'file_count')::int
FROM (SELECT $1::jsonb AS d) input
`

func (q *Queries) CreateImportSkill(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, createImportSkill, data)
	return err
}

const getImportHistory = `-- name: GetImportHistory :one
SELECT to_jsonb(i) FROM resource_imports i WHERE id = $1::uuid
`

func (q *Queries) GetImportHistory(ctx context.Context, dollar_1 string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getImportHistory, dollar_1)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const getImportSkillSHA = `-- name: GetImportSkillSHA :one
SELECT package_sha256 FROM skills WHERE id=$1::uuid
`

func (q *Queries) GetImportSkillSHA(ctx context.Context, dollar_1 string) (string, error) {
	row := q.db.QueryRow(ctx, getImportSkillSHA, dollar_1)
	var package_sha256 string
	err := row.Scan(&package_sha256)
	return package_sha256, err
}

const getImportTarget = `-- name: GetImportTarget :one
SELECT data FROM (
    SELECT id, to_jsonb(s) AS data FROM skills s WHERE $1::text = 'skill' AND id = $2::uuid AND deleted_at IS NULL
    UNION ALL
    SELECT id, to_jsonb(r) AS data FROM rules r WHERE $1::text = 'rule' AND id = $2::uuid AND deleted_at IS NULL
    UNION ALL
    SELECT id, to_jsonb(c) AS data FROM connectors c WHERE $1::text = 'connector' AND id = $2::uuid AND deleted_at IS NULL
    UNION ALL
    SELECT id, to_jsonb(e) AS data FROM experts e WHERE $1::text = 'expert' AND id = $2::uuid AND deleted_at IS NULL
) t LIMIT 1
`

type GetImportTargetParams struct {
	Column1 string
	Column2 string
}

func (q *Queries) GetImportTarget(ctx context.Context, arg GetImportTargetParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getImportTarget, arg.Column1, arg.Column2)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getLatestImport = `-- name: GetLatestImport :one
SELECT version, release_id::text AS release_id, manifest_sha256
FROM resource_imports WHERE publisher = $1 AND status = 'succeeded'
ORDER BY version DESC LIMIT 1
`

type GetLatestImportRow struct {
	Version        int64
	ReleaseID      string
	ManifestSha256 string
}

func (q *Queries) GetLatestImport(ctx context.Context, publisher string) (GetLatestImportRow, error) {
	row := q.db.QueryRow(ctx, getLatestImport, publisher)
	var i GetLatestImportRow
	err := row.Scan(&i.Version, &i.ReleaseID, &i.ManifestSha256)
	return i, err
}

const invalidateImportTools = `-- name: InvalidateImportTools :exec
UPDATE mcp_tools SET deleted_at=now() WHERE connector_id=$1::uuid AND deleted_at IS NULL
`

func (q *Queries) InvalidateImportTools(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, invalidateImportTools, dollar_1)
	return err
}

const linkImportExpertConnector = `-- name: LinkImportExpertConnector :exec
INSERT INTO expert_connectors(expert_id,connector_id) VALUES ($1::uuid,$2::uuid)
`

type LinkImportExpertConnectorParams struct {
	Column1 string
	Column2 string
}

func (q *Queries) LinkImportExpertConnector(ctx context.Context, arg LinkImportExpertConnectorParams) error {
	_, err := q.db.Exec(ctx, linkImportExpertConnector, arg.Column1, arg.Column2)
	return err
}

const linkImportExpertRule = `-- name: LinkImportExpertRule :exec
INSERT INTO expert_rules(expert_id,rule_id) VALUES ($1::uuid,$2::uuid)
`

type LinkImportExpertRuleParams struct {
	Column1 string
	Column2 string
}

func (q *Queries) LinkImportExpertRule(ctx context.Context, arg LinkImportExpertRuleParams) error {
	_, err := q.db.Exec(ctx, linkImportExpertRule, arg.Column1, arg.Column2)
	return err
}

const linkImportExpertSkill = `-- name: LinkImportExpertSkill :exec
INSERT INTO expert_skills(expert_id,skill_id) VALUES ($1::uuid,$2::uuid)
`

type LinkImportExpertSkillParams struct {
	Column1 string
	Column2 string
}

func (q *Queries) LinkImportExpertSkill(ctx context.Context, arg LinkImportExpertSkillParams) error {
	_, err := q.db.Exec(ctx, linkImportExpertSkill, arg.Column1, arg.Column2)
	return err
}

const listImportBindings = `-- name: ListImportBindings :many
SELECT to_jsonb(b) FROM resource_import_bindings b WHERE publisher = $1 ORDER BY slug
`

func (q *Queries) ListImportBindings(ctx context.Context, publisher string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listImportBindings, publisher)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportHistory = `-- name: ListImportHistory :many
SELECT to_jsonb(i) FROM resource_imports i ORDER BY created_at DESC, id DESC LIMIT 100
`

func (q *Queries) ListImportHistory(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listImportHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportReferences = `-- name: ListImportReferences :many
SELECT id FROM (
    SELECT e.id::text AS id FROM expert_skills l JOIN experts e ON e.id=l.expert_id
    WHERE $1::text='skill' AND l.skill_id=$2::uuid AND e.deleted_at IS NULL AND e.enabled
    UNION ALL
    SELECT e.id::text AS id FROM expert_rules l JOIN experts e ON e.id=l.expert_id
    WHERE $1::text='rule' AND l.rule_id=$2::uuid AND e.deleted_at IS NULL AND e.enabled
    UNION ALL
    SELECT e.id::text AS id FROM expert_connectors l JOIN experts e ON e.id=l.expert_id
    WHERE $1::text='connector' AND l.connector_id=$2::uuid AND e.deleted_at IS NULL AND e.enabled
) refs
`

type ListImportReferencesParams struct {
	Column1 string
	Column2 string
}

func (q *Queries) ListImportReferences(ctx context.Context, arg ListImportReferencesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listImportReferences, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockImportConnector = `-- name: LockImportConnector :one
SELECT id::text FROM connectors WHERE id = $1::uuid FOR UPDATE
`

func (q *Queries) LockImportConnector(ctx context.Context, dollar_1 string) (string, error) {
	row := q.db.QueryRow(ctx, lockImportConnector, dollar_1)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockImportExpert = `-- name: LockImportExpert :one
SELECT id::text FROM experts WHERE id = $1::uuid FOR UPDATE
`

func (q *Queries) LockImportExpert(ctx context.Context, dollar_1 string) (string, error) {
	row := q.db.QueryRow(ctx, lockImportExpert, dollar_1)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockImportPublisher = `-- name: LockImportPublisher :one
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) LockImportPublisher(ctx context.Context, dollar_1 int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockImportPublisher, dollar_1)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const lockImportRule = `-- name: LockImportRule :one
SELECT id::text FROM rules WHERE id = $1::uuid FOR UPDATE
`

func (q *Queries) LockImportRule(ctx context.Context, dollar_1 string) (string, error) {
	row := q.db.QueryRow(ctx, lockImportRule, dollar_1)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockImportSkill = `-- name: LockImportSkill :one
SELECT id::text FROM skills WHERE id = $1::uuid FOR UPDATE
`

func (q *Queries) LockImportSkill(ctx context.Context, dollar_1 string) (string, error) {
	row := q.db.QueryRow(ctx, lockImportSkill, dollar_1)
	var id string
	err := row.Scan(&id)
	return id, err
}

const retireImportBinding = `-- name: RetireImportBinding :exec
UPDATE resource_import_bindings SET retired_at=now(),retired_import_id=$1::uuid,
    last_import_id=$1::uuid,updated_at=now()
WHERE publisher=$2 AND slug=$3
`

type RetireImportBindingParams struct {
	ImportID  string
	Publisher string
	Slug      string
}

func (q *Queries) RetireImportBinding(ctx context.Context, arg RetireImportBindingParams) error {
	_, err := q.db.Exec(ctx, retireImportBinding, arg.ImportID, arg.Publisher, arg.Slug)
	return err
}

const retireImportConnector = `-- name: RetireImportConnector :exec
UPDATE connectors SET enabled=false,revision=revision+1,updated_at=now() WHERE id=$1::uuid
`

func (q *Queries) RetireImportConnector(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, retireImportConnector, dollar_1)
	return err
}

const retireImportExpert = `-- name: RetireImportExpert :exec
UPDATE experts SET enabled=false,revision=revision+1,updated_at=now() WHERE id=$1::uuid
`

func (q *Queries) RetireImportExpert(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, retireImportExpert, dollar_1)
	return err
}

const retireImportRule = `-- name: RetireImportRule :exec
UPDATE rules SET enabled=false,revision=revision+1,updated_at=now() WHERE id=$1::uuid
`

func (q *Queries) RetireImportRule(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, retireImportRule, dollar_1)
	return err
}

const retireImportSkill = `-- name: RetireImportSkill :exec
UPDATE skills SET enabled=false,revision=revision+1,updated_at=now() WHERE id=$1::uuid
`

func (q *Queries) RetireImportSkill(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, retireImportSkill, dollar_1)
	return err
}

const revokeImportCredentials = `-- name: RevokeImportCredentials :exec
UPDATE connector_credentials SET revoked_at=now(),revision=revision+1,updated_at=now()
WHERE connector_id=$1::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeImportCredentials(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, revokeImportCredentials, dollar_1)
	return err
}

const updateImportConnector = `-- name: UpdateImportConnector :exec
UPDATE connectors SET name=d->>'name',description='',url=d->>'url',authorization_mode=d->>'authorization_mode',
       authorization_method=NULLIF(d->>'authorization_method',''),oauth_config=d->'oauth_config',timeout_ms=(d->>'timeout_ms')::int,
       auth_header_name=d->>'auth_header_name',name_i18n=d->'name_i18n',description_i18n=d->'description_i18n',
       config_revision=(d->>'config_revision')::bigint,connection_status=d->>'connection_status',
       last_checked_at=CASE WHEN (d->>'config_changed')::boolean THEN NULL ELSE last_checked_at END,
       last_error=CASE WHEN (d->>'config_changed')::boolean THEN NULL ELSE last_error END,
       enabled=true,revision=revision+1,updated_at=now()
FROM (SELECT $1::jsonb AS d) input WHERE id=(d->>'id')::uuid
`

func (q *Queries) UpdateImportConnector(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateImportConnector, data)
	return err
}

const updateImportExpert = `-- name: UpdateImportExpert :exec
UPDATE experts SET name=d->>'name',description=d->>'description',prompt=d->>'prompt',avatar_s3_key=d->>'avatar_s3_key',
       name_i18n=d->'name_i18n',description_i18n=d->'description_i18n',enabled=true,revision=revision+1,updated_at=now()
FROM (SELECT $1::jsonb AS d) input WHERE id=(d->>'id')::uuid
`

func (q *Queries) UpdateImportExpert(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateImportExpert, data)
	return err
}

const updateImportRule = `-- name: UpdateImportRule :exec
UPDATE rules SET name=d->>'name',content=d->>'content',name_i18n=d->'name_i18n',description_i18n=d->'description_i18n',
       enabled=true,revision=revision+1,updated_at=now()
FROM (SELECT $1::jsonb AS d) input WHERE id=(d->>'id')::uuid
`

func (q *Queries) UpdateImportRule(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateImportRule, data)
	return err
}

const updateImportSkill = `-- name: UpdateImportSkill :exec
UPDATE skills SET name=d->>'name',description=d->>'description',name_i18n=d->'name_i18n',description_i18n=d->'description_i18n',
       package_file_name=d->>'package_file_name',package_s3_key=CASE WHEN d->>'package_s3_key'='' THEN package_s3_key ELSE d->>'package_s3_key' END,
       package_size_bytes=(d->>'package_size_bytes')::bigint,package_sha256=d->>'package_sha256',file_count=(d->>'file_count')::int,
       enabled=true,revision=revision+1,updated_at=now()
FROM (SELECT $1::jsonb AS d) input WHERE id=(d->>'id')::uuid
`

func (q *Queries) UpdateImportSkill(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateImportSkill, data)
	return err
}

const upsertImportBinding = `-- name: UpsertImportBinding :exec
INSERT INTO resource_import_bindings(publisher,slug,resource_type,resource_id,source_sha256,applied_sha256,last_import_id)
SELECT d->>'publisher',d->>'slug',d->>'resource_type',(d->>'resource_id')::uuid,d->>'source_sha256',d->>'applied_sha256',(d->>'last_import_id')::uuid
FROM (SELECT $1::jsonb AS d) input
ON CONFLICT (publisher,slug) DO UPDATE SET source_sha256=EXCLUDED.source_sha256,
    applied_sha256=EXCLUDED.applied_sha256,last_import_id=EXCLUDED.last_import_id,
    retired_at=NULL,retired_import_id=NULL,updated_at=now()
`

func (q *Queries) UpsertImportBinding(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, upsertImportBinding, data)
	return err
}
