// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Setting struct {
	ID              string
	Key             string
	Value           []byte
	SchemaVersion   int32
	UpdatedByUserID string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Revision        int64
}
