// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const claimVideoJobPoll = `-- name: ClaimVideoJobPoll :one
UPDATE video_jobs SET poll_after=now()+interval '5 minutes'
WHERE id=$1 AND poll_after<=now() AND status IN ('submitted','running')
RETURNING model_id,provider_job_id,billing_transaction_id,user_id
`

type ClaimVideoJobPollRow struct {
	ModelID              string
	ProviderJobID        *string
	BillingTransactionID *string
	UserID               string
}

func (q *Queries) ClaimVideoJobPoll(ctx context.Context, id string) (ClaimVideoJobPollRow, error) {
	row := q.db.QueryRow(ctx, claimVideoJobPoll, id)
	var i ClaimVideoJobPollRow
	err := row.Scan(
		&i.ModelID,
		&i.ProviderJobID,
		&i.BillingTransactionID,
		&i.UserID,
	)
	return i, err
}

const expiredVideoInputs = `-- name: ExpiredVideoInputs :many
SELECT i.id,i.object_key FROM video_inputs i
WHERE i.expires_at<now() AND NOT EXISTS (
    SELECT 1 FROM video_job_inputs j JOIN video_jobs v ON v.id=j.job_id
    WHERE j.input_id=i.id AND v.status IN ('created','reserved','submitted','running','unknown')) LIMIT 50
`

type ExpiredVideoInputsRow struct {
	ID        string
	ObjectKey string
}

func (q *Queries) ExpiredVideoInputs(ctx context.Context) ([]ExpiredVideoInputsRow, error) {
	rows, err := q.db.Query(ctx, expiredVideoInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredVideoInputsRow{}
	for rows.Next() {
		var i ExpiredVideoInputsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredVideoOutputs = `-- name: ExpiredVideoOutputs :many
SELECT id,object_key FROM video_outputs WHERE expires_at<now() AND purged_at IS NULL LIMIT 50
`

type ExpiredVideoOutputsRow struct {
	ID        string
	ObjectKey string
}

func (q *Queries) ExpiredVideoOutputs(ctx context.Context) ([]ExpiredVideoOutputsRow, error) {
	rows, err := q.db.Query(ctx, expiredVideoOutputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredVideoOutputsRow{}
	for rows.Next() {
		var i ExpiredVideoOutputsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const idempotentVideoJob = `-- name: IdempotentVideoJob :one
SELECT id,request_hash FROM video_jobs WHERE user_id=$1 AND idempotency_key=$2
`

type IdempotentVideoJobParams struct {
	UserID         string
	IdempotencyKey *string
}

type IdempotentVideoJobRow struct {
	ID          string
	RequestHash string
}

func (q *Queries) IdempotentVideoJob(ctx context.Context, arg IdempotentVideoJobParams) (IdempotentVideoJobRow, error) {
	row := q.db.QueryRow(ctx, idempotentVideoJob, arg.UserID, arg.IdempotencyKey)
	var i IdempotentVideoJobRow
	err := row.Scan(&i.ID, &i.RequestHash)
	return i, err
}

const insertVideoInput = `-- name: InsertVideoInput :exec
INSERT INTO video_inputs (id,user_id,object_key,mime_type,width,height,byte_size,sha256,expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertVideoInputParams struct {
	ID        string
	UserID    string
	ObjectKey string
	MimeType  string
	Width     int32
	Height    int32
	ByteSize  int64
	Sha256    string
	ExpiresAt time.Time
}

func (q *Queries) InsertVideoInput(ctx context.Context, arg InsertVideoInputParams) error {
	_, err := q.db.Exec(ctx, insertVideoInput,
		arg.ID,
		arg.UserID,
		arg.ObjectKey,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.ByteSize,
		arg.Sha256,
		arg.ExpiresAt,
	)
	return err
}

const insertVideoJob = `-- name: InsertVideoJob :exec
INSERT INTO video_jobs(id,user_id,model_id,session_id,provider,mode,status,request_hash,idempotency_key,request_config,pricing_snapshot,billing_transaction_id)
VALUES($1::uuid,$2::uuid,$3::uuid,
NULLIF($4::text,'')::uuid,$5::text,$6::text,
'reserved',$7::text,NULLIF($8::text,''),
$9::jsonb,$10::jsonb,$11::uuid)
`

type InsertVideoJobParams struct {
	ID                   string
	UserID               string
	ModelID              string
	SessionID            string
	Provider             string
	Mode                 string
	RequestHash          string
	IdempotencyKey       string
	RequestConfig        []byte
	PricingSnapshot      []byte
	BillingTransactionID string
}

func (q *Queries) InsertVideoJob(ctx context.Context, arg InsertVideoJobParams) error {
	_, err := q.db.Exec(ctx, insertVideoJob,
		arg.ID,
		arg.UserID,
		arg.ModelID,
		arg.SessionID,
		arg.Provider,
		arg.Mode,
		arg.RequestHash,
		arg.IdempotencyKey,
		arg.RequestConfig,
		arg.PricingSnapshot,
		arg.BillingTransactionID,
	)
	return err
}

const insertVideoJobInput = `-- name: InsertVideoJobInput :exec
INSERT INTO video_job_inputs(job_id,input_id,ordinal,role) VALUES($1,$2,$3,$4)
`

type InsertVideoJobInputParams struct {
	JobID   string
	InputID string
	Ordinal int32
	Role    string
}

func (q *Queries) InsertVideoJobInput(ctx context.Context, arg InsertVideoJobInputParams) error {
	_, err := q.db.Exec(ctx, insertVideoJobInput,
		arg.JobID,
		arg.InputID,
		arg.Ordinal,
		arg.Role,
	)
	return err
}

const insertVideoOutput = `-- name: InsertVideoOutput :exec
INSERT INTO video_outputs(id,job_id,object_key,mime_type,width,height,duration_ms,byte_size,sha256,expires_at)
VALUES($1,$2,$3,'video/mp4',$4,$5,$6,$7,$8,$9)
`

type InsertVideoOutputParams struct {
	ID         string
	JobID      string
	ObjectKey  string
	Width      int32
	Height     int32
	DurationMs int64
	ByteSize   int64
	Sha256     string
	ExpiresAt  time.Time
}

func (q *Queries) InsertVideoOutput(ctx context.Context, arg InsertVideoOutputParams) error {
	_, err := q.db.Exec(ctx, insertVideoOutput,
		arg.ID,
		arg.JobID,
		arg.ObjectKey,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.ByteSize,
		arg.Sha256,
		arg.ExpiresAt,
	)
	return err
}

const markAbandonedVideoJobs = `-- name: MarkAbandonedVideoJobs :exec
UPDATE video_jobs SET status='unknown',error_code='provider_submit_unknown',updated_at=now()
WHERE status='reserved' AND provider_job_id IS NULL AND updated_at<now()-interval '2 minutes'
`

func (q *Queries) MarkAbandonedVideoJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markAbandonedVideoJobs)
	return err
}

const markVideoJobFailed = `-- name: MarkVideoJobFailed :exec
UPDATE video_jobs SET status='failed',error_code=$2,updated_at=now(),completed_at=now() WHERE id=$1
`

type MarkVideoJobFailedParams struct {
	ID        string
	ErrorCode *string
}

func (q *Queries) MarkVideoJobFailed(ctx context.Context, arg MarkVideoJobFailedParams) error {
	_, err := q.db.Exec(ctx, markVideoJobFailed, arg.ID, arg.ErrorCode)
	return err
}

const markVideoJobRunning = `-- name: MarkVideoJobRunning :exec
UPDATE video_jobs SET status='running',updated_at=now(),poll_after=now()+interval '10 seconds' WHERE id=$1
`

func (q *Queries) MarkVideoJobRunning(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markVideoJobRunning, id)
	return err
}

const markVideoJobSubmitted = `-- name: MarkVideoJobSubmitted :execrows
UPDATE video_jobs SET status='submitted',provider_job_id=$2,updated_at=now(),poll_after=now()
WHERE id=$1 AND status='reserved'
`

type MarkVideoJobSubmittedParams struct {
	ID            string
	ProviderJobID *string
}

func (q *Queries) MarkVideoJobSubmitted(ctx context.Context, arg MarkVideoJobSubmittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markVideoJobSubmitted, arg.ID, arg.ProviderJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markVideoJobSucceeded = `-- name: MarkVideoJobSucceeded :exec
UPDATE video_jobs SET status='succeeded',output_duration_ms=$2,updated_at=now(),completed_at=now()
WHERE id=$1 AND status IN ('submitted','running')
`

type MarkVideoJobSucceededParams struct {
	ID               string
	OutputDurationMs *int64
}

func (q *Queries) MarkVideoJobSucceeded(ctx context.Context, arg MarkVideoJobSucceededParams) error {
	_, err := q.db.Exec(ctx, markVideoJobSucceeded, arg.ID, arg.OutputDurationMs)
	return err
}

const markVideoJobUnknown = `-- name: MarkVideoJobUnknown :exec
UPDATE video_jobs SET status='unknown',error_code=$2,updated_at=now() WHERE id=$1
`

type MarkVideoJobUnknownParams struct {
	ID        string
	ErrorCode *string
}

func (q *Queries) MarkVideoJobUnknown(ctx context.Context, arg MarkVideoJobUnknownParams) error {
	_, err := q.db.Exec(ctx, markVideoJobUnknown, arg.ID, arg.ErrorCode)
	return err
}

const markVideoOutputPurged = `-- name: MarkVideoOutputPurged :exec
UPDATE video_outputs SET purged_at=now() WHERE id=$1 AND purged_at IS NULL
`

func (q *Queries) MarkVideoOutputPurged(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markVideoOutputPurged, id)
	return err
}

const pollableVideoJobs = `-- name: PollableVideoJobs :many
SELECT id FROM video_jobs WHERE status IN ('submitted','running')
AND provider_job_id IS NOT NULL AND poll_after<=now() ORDER BY poll_after LIMIT 20
`

func (q *Queries) PollableVideoJobs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, pollableVideoJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeExpiredVideoInput = `-- name: RemoveExpiredVideoInput :exec
DELETE FROM video_inputs WHERE id=$1
`

func (q *Queries) RemoveExpiredVideoInput(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, removeExpiredVideoInput, id)
	return err
}

const retryVideoJobPoll = `-- name: RetryVideoJobPoll :exec
UPDATE video_jobs SET poll_after=now()+interval '30 seconds' WHERE id=$1 AND status IN ('submitted','running')
`

func (q *Queries) RetryVideoJobPoll(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, retryVideoJobPoll, id)
	return err
}

const unlinkExpiredVideoInput = `-- name: UnlinkExpiredVideoInput :exec
DELETE FROM video_job_inputs WHERE input_id=$1
`

func (q *Queries) UnlinkExpiredVideoInput(ctx context.Context, inputID string) error {
	_, err := q.db.Exec(ctx, unlinkExpiredVideoInput, inputID)
	return err
}

const videoInputOwned = `-- name: VideoInputOwned :one
SELECT object_key,mime_type,width,height,byte_size,sha256 FROM video_inputs
WHERE id=$1 AND user_id=$2 AND expires_at>now()
`

type VideoInputOwnedParams struct {
	ID     string
	UserID string
}

type VideoInputOwnedRow struct {
	ObjectKey string
	MimeType  string
	Width     int32
	Height    int32
	ByteSize  int64
	Sha256    string
}

func (q *Queries) VideoInputOwned(ctx context.Context, arg VideoInputOwnedParams) (VideoInputOwnedRow, error) {
	row := q.db.QueryRow(ctx, videoInputOwned, arg.ID, arg.UserID)
	var i VideoInputOwnedRow
	err := row.Scan(
		&i.ObjectKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.Sha256,
	)
	return i, err
}

const videoJobOutputDuration = `-- name: VideoJobOutputDuration :one
SELECT duration_ms FROM video_outputs WHERE job_id=$1
`

func (q *Queries) VideoJobOutputDuration(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRow(ctx, videoJobOutputDuration, jobID)
	var duration_ms int64
	err := row.Scan(&duration_ms)
	return duration_ms, err
}

const videoOutputOwned = `-- name: VideoOutputOwned :one
SELECT o.object_key,o.mime_type,o.byte_size FROM video_outputs o
JOIN video_jobs j ON j.id=o.job_id WHERE o.id=$1 AND j.user_id=$2
AND o.expires_at>now() AND o.purged_at IS NULL AND j.status='succeeded'
`

type VideoOutputOwnedParams struct {
	ID     string
	UserID string
}

type VideoOutputOwnedRow struct {
	ObjectKey string
	MimeType  string
	ByteSize  int64
}

func (q *Queries) VideoOutputOwned(ctx context.Context, arg VideoOutputOwnedParams) (VideoOutputOwnedRow, error) {
	row := q.db.QueryRow(ctx, videoOutputOwned, arg.ID, arg.UserID)
	var i VideoOutputOwnedRow
	err := row.Scan(&i.ObjectKey, &i.MimeType, &i.ByteSize)
	return i, err
}

const videoTaskOwned = `-- name: VideoTaskOwned :one
SELECT j.status,j.mode,j.created_at,j.completed_at,j.error_code,j.billing_transaction_id,
j.request_config,j.pricing_snapshot,o.id AS output_id,o.mime_type,o.width,o.height,o.duration_ms,o.byte_size,o.expires_at
FROM video_jobs j LEFT JOIN video_outputs o ON o.job_id=j.id
WHERE j.id=$1 AND j.user_id=$2
`

type VideoTaskOwnedParams struct {
	ID     string
	UserID string
}

type VideoTaskOwnedRow struct {
	Status               string
	Mode                 string
	CreatedAt            time.Time
	CompletedAt          *time.Time
	ErrorCode            *string
	BillingTransactionID *string
	RequestConfig        []byte
	PricingSnapshot      []byte
	OutputID             *string
	MimeType             *string
	Width                *int32
	Height               *int32
	DurationMs           *int64
	ByteSize             *int64
	ExpiresAt            *time.Time
}

func (q *Queries) VideoTaskOwned(ctx context.Context, arg VideoTaskOwnedParams) (VideoTaskOwnedRow, error) {
	row := q.db.QueryRow(ctx, videoTaskOwned, arg.ID, arg.UserID)
	var i VideoTaskOwnedRow
	err := row.Scan(
		&i.Status,
		&i.Mode,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.BillingTransactionID,
		&i.RequestConfig,
		&i.PricingSnapshot,
		&i.OutputID,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.ByteSize,
		&i.ExpiresAt,
	)
	return i, err
}
