// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Feedback struct {
	ID             string
	UserID         string
	Category       string
	Content        string
	Rating         *int32
	Platform       string
	ClientVersion  string
	State          string
	RequestID      string
	IdempotencyKey string
	RequestHash    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type FeedbackAttachment struct {
	ID         string
	FeedbackID string
	ObjectKey  string
	MimeType   string
	ByteSize   int64
	Width      int32
	Height     int32
	Sha256     string
	State      string
	CreatedAt  time.Time
}
