name: monkeycode_runner
services:
  orchestrator:
    image: ${ORCHESTRATOR_IMAGE}
    container_name: monkeycode-orchestrator
    restart: always
    init: true
    environment:
      - ORCHESTRATOR_GRPC_URL=${GRPC_URL}
      - ORCHESTRATOR_AUTH_TOKEN=${TOKEN}
      - ORCHESTRATOR_TYPE=docker
      - ORCHESTRATOR_LOG_LEVEL=debug
      - ORCHESTRATOR_GRPC_PROXY=${GRPC_PROXY:-}
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
