// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createGrant = `-- name: CreateGrant :execresult
INSERT INTO resource_access_grants (resource_type, resource_id, user_id, group_id, access_level, usage_requirement,
    granted_by_user_id)
    VALUES ($1, $2, NULLIF ($3::text,
	'')::UUID,NULLIF($4::text,'')::uuid, 'read_only', $5, $6)
`

type CreateGrantParams struct {
	ResourceType     string
	ResourceID       string
	UserID           string
	GroupID          string
	UsageRequirement string
	GrantedByUserID  string
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createGrant,
		arg.ResourceType,
		arg.ResourceID,
		arg.UserID,
		arg.GroupID,
		arg.UsageRequirement,
		arg.GrantedByUserID,
	)
}

const createShares = `-- name: CreateShares :execresult
INSERT INTO resource_access_grants (resource_type, resource_id, user_id, access_level, granted_by_user_id)
SELECT
    $1,
    $2,
    u.id,
    'read_only',
    $3
FROM
    users u
WHERE
    u.id::text = ANY ($4::text[])
ON CONFLICT (resource_type,
    resource_id,
    user_id)
WHERE
    user_id IS NOT NULL
        DO NOTHING
`

type CreateSharesParams struct {
	ResourceType    string
	ResourceID      string
	GrantedByUserID string
	UserIds         []string
}

func (q *Queries) CreateShares(ctx context.Context, arg CreateSharesParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createShares,
		arg.ResourceType,
		arg.ResourceID,
		arg.GrantedByUserID,
		arg.UserIds,
	)
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, created_by_user_id)
    VALUES ($1, $2)
RETURNING
    jsonb_build_object('id', id, 'name', name)
`

type CreateTagParams struct {
	Name            string
	CreatedByUserID string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.CreatedByUserID)
	var jsonb_build_object []byte
	err := row.Scan(&jsonb_build_object)
	return jsonb_build_object, err
}

const deleteGrants = `-- name: DeleteGrants :execresult
DELETE FROM resource_access_grants
WHERE resource_type = $1
    AND resource_id = $2
`

type DeleteGrantsParams struct {
	ResourceType string
	ResourceID   string
}

func (q *Queries) DeleteGrants(ctx context.Context, arg DeleteGrantsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteGrants, arg.ResourceType, arg.ResourceID)
}

const deleteTag = `-- name: DeleteTag :one
UPDATE
    tags
SET
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
RETURNING
    jsonb_build_object('id', id)
`

func (q *Queries) DeleteTag(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteTag, id)
	var jsonb_build_object []byte
	err := row.Scan(&jsonb_build_object)
	return jsonb_build_object, err
}

const getOwnerName = `-- name: GetOwnerName :one
SELECT
    name
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetOwnerName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getOwnerName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const hasAccess = `-- name: HasAccess :one
WITH RECURSIVE user_groups (
    group_id
) AS (
    SELECT
        id
    FROM
        GROUPS
    WHERE
        deleted_at IS NULL
        AND id IN (
            SELECT
                group_id
            FROM
                group_users
            WHERE
                user_id = $1
                AND removed_at IS NULL)
        UNION
        SELECT
            parent.id
        FROM
            GROUPS g
            JOIN user_groups ug ON ug.group_id = g.id
            JOIN GROUPS parent ON parent.id = g.parent_id
        WHERE
            g.deleted_at IS NULL
            AND parent.deleted_at IS NULL
)
SELECT
    EXISTS (
        SELECT
            1
        FROM
            resource_access_grants rag
        WHERE
            rag.resource_type = $2
            AND rag.resource_id = $3
            AND (rag.user_id = $1
                OR rag.group_id IN (
                    SELECT
                        group_id
                    FROM
                        user_groups)))
`

type HasAccessParams struct {
	UserID       *string
	ResourceType string
	ResourceID   string
}

func (q *Queries) HasAccess(ctx context.Context, arg HasAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAccess, arg.UserID, arg.ResourceType, arg.ResourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGrants = `-- name: ListGrants :many
SELECT
    jsonb_build_object('user_id', user_id, 'group_id', group_id, 'usage_requirement', usage_requirement)
FROM
    resource_access_grants
WHERE
    resource_type = $1
    AND resource_id = $2
ORDER BY
    group_id,
    user_id
`

type ListGrantsParams struct {
	ResourceType string
	ResourceID   string
}

func (q *Queries) ListGrants(ctx context.Context, arg ListGrantsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listGrants, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT
    jsonb_build_object('id', id, 'parent_id', parent_id, 'name', name)
FROM
    GROUPS
WHERE
    deleted_at IS NULL
ORDER BY
    name,
    id
`

func (q *Queries) ListGroups(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT
    jsonb_build_object('id', id, 'name', name)
FROM
    tags
WHERE
    deleted_at IS NULL
ORDER BY
    lower(name),
    id
`

func (q *Queries) ListTags(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
    jsonb_build_object('id', id, 'name', name, 'email', email)
FROM
    users
WHERE
    deleted_at IS NULL
    AND status = 'active'
ORDER BY
    name,
    id
`

func (q *Queries) ListUsers(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecipients = `-- name: LockRecipients :many
SELECT
    id
FROM
    users
WHERE
    id::text = ANY ($1::text[])
    AND deleted_at IS NULL
    AND status = 'active'
ORDER BY
    id FOR SHARE
`

func (q *Queries) LockRecipients(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockRecipients, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShares = `-- name: RevokeShares :execresult
DELETE FROM resource_access_grants
WHERE resource_type = $1
    AND resource_id = $2
    AND user_id::text = ANY ($3::text[])
`

type RevokeSharesParams struct {
	ResourceType string
	ResourceID   string
	UserIds      []string
}

func (q *Queries) RevokeShares(ctx context.Context, arg RevokeSharesParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, revokeShares, arg.ResourceType, arg.ResourceID, arg.UserIds)
}

const subjectExists = `-- name: SubjectExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            id = NULLIF ($1::text, '')::uuid
            AND deleted_at IS NULL
            AND status = 'active'
        UNION ALL
        SELECT
            1
        FROM
            GROUPS
        WHERE
            id = NULLIF ($2::text, '')::uuid
            AND deleted_at IS NULL)
`

type SubjectExistsParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) SubjectExists(ctx context.Context, arg SubjectExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, subjectExists, arg.UserID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE
    tags
SET
    name = $2,
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
RETURNING
    jsonb_build_object('id', id, 'name', name)
`

type UpdateTagParams struct {
	ID   string
	Name string
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name)
	var jsonb_build_object []byte
	err := row.Scan(&jsonb_build_object)
	return jsonb_build_object, err
}
