[err-permission]
other = "Permission denied"

[err-user-not-found]
other = "User not found"

[err-user-lock]
other = "User is locked"

[err-account-already-exist]
other = "Account already exists"

[err-password]
other = "Incorrect password"

[err-only-admin]
other = "Only admin can perform this operation"

[err-invite-code-invalid]
other = "Invalid invitation code"

[err-email-invalid]
other = "Invalid email format"

[err-oauth-state-invalid]
other = "Invalid OAuth state"

[err-unsupported-platform]
other = "Unsupported platform"

[err-not-invited]
other = "Not invited"

[err-dingtalk-not-enabled]
other = "DingTalk is not enabled"

[err-custom-not-enabled]
other = "OAuth is not enabled"

[err-user-limit]
other = "User limit reached"

[err-model-limit]
other = "Model limit reached"

[err-security-limit]
other = "Security limit reached"

[err-only-enterprise]
other = "Only enterprise user can perform this operation"

[err-invalid-secret]
other = "Invalid secret"

[err-ai-employee-limit]
other = "AI employee limit reached"