// Code generated by ent, DO NOT EDIT.

package licenseaudit

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the licenseaudit type in the database.
	Label = "license_audit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLicenseID holds the string denoting the license_id field in the database.
	FieldLicenseID = "license_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the licenseaudit in the database.
	Table = "license_audits"
)

// Columns holds all SQL columns for licenseaudit fields.
var Columns = []string{
	FieldID,
	FieldLicenseID,
	FieldAction,
	FieldResult,
	FieldMessage,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Action defines the type for the "action" enum field.
type Action string

// Action values.
const (
	ActionExportMachineCode Action = "export_machine_code"
	ActionImportLicense     Action = "import_license"
	ActionViewStatus        Action = "view_status"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionExportMachineCode, ActionImportLicense, ActionViewStatus:
		return nil
	default:
		return fmt.Errorf("licenseaudit: invalid enum value for action field: %q", a)
	}
}

// Result defines the type for the "result" enum field.
type Result string

// Result values.
const (
	ResultSuccess Result = "success"
	ResultFailed  Result = "failed"
)

func (r Result) String() string {
	return string(r)
}

// ResultValidator is a validator for the "result" field enum values. It is called by the builders before save.
func ResultValidator(r Result) error {
	switch r {
	case ResultSuccess, ResultFailed:
		return nil
	default:
		return fmt.Errorf("licenseaudit: invalid enum value for result field: %q", r)
	}
}

// OrderOption defines the ordering options for the LicenseAudit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLicenseID orders the results by the license_id field.
func ByLicenseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByResult orders the results by the result field.
func ByResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResult, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
