// Code generated by ent, DO NOT EDIT.

package licenseinstallation

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the licenseinstallation type in the database.
	Label = "license_installation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstallationID holds the string denoting the installation_id field in the database.
	FieldInstallationID = "installation_id"
	// FieldProduct holds the string denoting the product field in the database.
	FieldProduct = "product"
	// FieldProductVersion holds the string denoting the product_version field in the database.
	FieldProductVersion = "product_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the licenseinstallation in the database.
	Table = "license_installations"
)

// Columns holds all SQL columns for licenseinstallation fields.
var Columns = []string{
	FieldID,
	FieldInstallationID,
	FieldProduct,
	FieldProductVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// InstallationIDValidator is a validator for the "installation_id" field. It is called by the builders before save.
	InstallationIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Product defines the type for the "product" enum field.
type Product string

// Product values.
const (
	ProductMonkeycodeEnterprise Product = "monkeycode-enterprise"
)

func (pr Product) String() string {
	return string(pr)
}

// ProductValidator is a validator for the "product" field enum values. It is called by the builders before save.
func ProductValidator(pr Product) error {
	switch pr {
	case ProductMonkeycodeEnterprise:
		return nil
	default:
		return fmt.Errorf("licenseinstallation: invalid enum value for product field: %q", pr)
	}
}

// OrderOption defines the ordering options for the LicenseInstallation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstallationID orders the results by the installation_id field.
func ByInstallationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallationID, opts...).ToFunc()
}

// ByProduct orders the results by the product field.
func ByProduct(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProduct, opts...).ToFunc()
}

// ByProductVersion orders the results by the product_version field.
func ByProductVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
