// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createResource = `-- name: CreateResource :exec
INSERT INTO skills (name, description, package_file_name, package_s3_key, package_size_bytes, package_sha256,
    file_count, enabled, id, owner_user_id, ownership_type)
    VALUES (
        CASE WHEN $1::jsonb ? 'name' THEN
            ($1::jsonb ->> 'name')::text
        ELSE
            NULL
        END, CASE WHEN $1::jsonb ? 'description' THEN
            ($1::jsonb ->> 'description')::text
        ELSE
            NULL
        END, CASE WHEN $1::jsonb ? 'package_file_name' THEN
            ($1::jsonb ->> 'package_file_name')::text
        ELSE
            NULL
        END, CASE WHEN $1::jsonb ? 'package_s3_key' THEN
            ($1::jsonb ->> 'package_s3_key')::text
        ELSE
            NULL
        END, CASE WHEN $1::jsonb ? 'package_size_bytes' THEN
            ($1::jsonb ->> 'package_size_bytes')::bigint
        ELSE
            NULL
        END, CASE WHEN $1::jsonb ? 'package_sha256' THEN
            ($1::jsonb ->> 'package_sha256')::text
        ELSE
            NULL
        END, CASE WHEN $1::jsonb ? 'file_count' THEN
            ($1::jsonb ->> 'file_count')::integer
        ELSE
            0
        END, CASE WHEN $1::jsonb ? 'enabled' THEN
            ($1::jsonb ->> 'enabled')::boolean
        ELSE
            TRUE
	END, ($1::jsonb ->> 'id')::uuid, ($1::jsonb ->>
	    'actor_id')::uuid, 'system')
`

func (q *Queries) CreateResource(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, createResource, data)
	return err
}

const createTagLink = `-- name: CreateTagLink :execresult
INSERT INTO resource_tags (resource_type, resource_id, tag_id, assigned_by_user_id)
    VALUES ('skill', $1, $2, $3)
`

type CreateTagLinkParams struct {
	ResourceID       string
	TagID            string
	AssignedByUserID string
}

func (q *Queries) CreateTagLink(ctx context.Context, arg CreateTagLinkParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createTagLink, arg.ResourceID, arg.TagID, arg.AssignedByUserID)
}

const deleteResource = `-- name: DeleteResource :exec
UPDATE
    skills
SET
    deleted_at = now(),
    updated_at = now(),
    revision = revision + 1
WHERE
    id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const deleteTags = `-- name: DeleteTags :execresult
DELETE FROM resource_tags
WHERE resource_type = 'skill'
    AND resource_id = $1
`

func (q *Queries) DeleteTags(ctx context.Context, resourceID string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteTags, resourceID)
}

const getResource = `-- name: GetResource :one
SELECT
    to_jsonb (t)
FROM
    skills t
WHERE
    id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetResource(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const getSkill = `-- name: GetSkill :one
SELECT
    to_jsonb (t)
FROM
    skills t
WHERE
    id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetSkill(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const listReferences = `-- name: ListReferences :many
SELECT
    jsonb_build_object('id', e.id, 'name', e.name)
FROM
    experts e
    JOIN expert_skills x ON x.expert_id = e.id
WHERE
    x.skill_id = $1
    AND e.deleted_at IS NULL
`

func (q *Queries) ListReferences(ctx context.Context, skillID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listReferences, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT
    to_jsonb (t)
FROM
    skills t
WHERE
    deleted_at IS NULL
ORDER BY
    lower(name),
    id
`

func (q *Queries) ListResources(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT
    jsonb_build_object('id', t.id, 'name', t.name)
FROM
    tags t
    JOIN resource_tags rt ON rt.tag_id = t.id
WHERE
    rt.resource_type = 'skill'
    AND rt.resource_id = $1
    AND t.deleted_at IS NULL
ORDER BY
    t.id
`

func (q *Queries) ListTags(ctx context.Context, resourceID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listTags, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var jsonb_build_object []byte
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResource = `-- name: LockResource :one
SELECT
    to_jsonb (t)
FROM
    skills t
WHERE
    id = $1
    AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockResource(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockResource, id)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const pageResources = `-- name: PageResources :many
SELECT
    to_jsonb (t)
FROM
    skills t
WHERE
    deleted_at IS NULL
    AND ($1::jsonb ->> 'ownership' = ''
        OR t.ownership_type = $1::jsonb ->> 'ownership')
    AND name ILIKE '%' || ($1::jsonb ->> 'search') || '%'
    AND id::text > $1::jsonb ->> 'cursor'
ORDER BY
    id
LIMIT ($1::jsonb ->> 'limit')::integer
`

func (q *Queries) PageResources(ctx context.Context, filter []byte) ([][]byte, error) {
	rows, err := q.db.Query(ctx, pageResources, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResourceEnabled = `-- name: SetResourceEnabled :exec
UPDATE
    skills
SET
    enabled = ($1::jsonb ->> 'enabled')::boolean,
    updated_at = now(),
    revision = revision + 1
WHERE
    id = ($1::jsonb ->> 'id')::uuid
`

func (q *Queries) SetResourceEnabled(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, setResourceEnabled, data)
	return err
}

const tagExists = `-- name: TagExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            tags
        WHERE
            id = $1
            AND deleted_at IS NULL)
`

func (q *Queries) TagExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, tagExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchResource = `-- name: TouchResource :exec
UPDATE
    skills
SET
    updated_at = now(),
    revision = revision + 1
WHERE
    id = $1
`

func (q *Queries) TouchResource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchResource, id)
	return err
}

const updateResource = `-- name: UpdateResource :exec
UPDATE
    skills
SET
    name = CASE WHEN $1::jsonb ? 'name' THEN
        ($1::jsonb ->> 'name')::text
    ELSE
        name
    END,
    description = CASE WHEN $1::jsonb ? 'description' THEN
        ($1::jsonb ->> 'description')::text
    ELSE
        description
    END,
    package_file_name = CASE WHEN $1::jsonb ? 'package_file_name' THEN
        ($1::jsonb ->> 'package_file_name')::text
    ELSE
        package_file_name
    END,
    package_s3_key = CASE WHEN $1::jsonb ? 'package_s3_key' THEN
        ($1::jsonb ->> 'package_s3_key')::text
    ELSE
        package_s3_key
    END,
    package_size_bytes = CASE WHEN $1::jsonb ? 'package_size_bytes' THEN
        ($1::jsonb ->> 'package_size_bytes')::bigint
    ELSE
        package_size_bytes
    END,
    package_sha256 = CASE WHEN $1::jsonb ? 'package_sha256' THEN
        ($1::jsonb ->> 'package_sha256')::text
    ELSE
        package_sha256
    END,
    file_count = CASE WHEN $1::jsonb ? 'file_count' THEN
        ($1::jsonb ->> 'file_count')::integer
    ELSE
        file_count
    END,
    enabled = CASE WHEN $1::jsonb ? 'enabled' THEN
        ($1::jsonb ->> 'enabled')::boolean
    ELSE
        enabled
    END,
    revision = revision + 1,
    updated_at = now()
WHERE
    id = ($1::jsonb ->> 'id')::uuid
`

func (q *Queries) UpdateResource(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateResource, data)
	return err
}
