// Code generated by ent, DO NOT EDIT.

package agentskillversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLTE(FieldID, id))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldResourceID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldVersion, v))
}

// S3Key applies equality check predicate on the "s3_key" field. It's identical to S3KeyEQ.
func S3Key(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldS3Key, v))
}

// GuardStatus applies equality check predicate on the "guard_status" field. It's identical to GuardStatusEQ.
func GuardStatus(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldGuardStatus, v))
}

// GuardTaskID applies equality check predicate on the "guard_task_id" field. It's identical to GuardTaskIDEQ.
func GuardTaskID(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldGuardTaskID, v))
}

// GuardDeadline applies equality check predicate on the "guard_deadline" field. It's identical to GuardDeadlineEQ.
func GuardDeadline(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldGuardDeadline, v))
}

// GuardError applies equality check predicate on the "guard_error" field. It's identical to GuardErrorEQ.
func GuardError(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldGuardError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...uuid.UUID) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldResourceID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContainsFold(FieldVersion, v))
}

// S3KeyEQ applies the EQ predicate on the "s3_key" field.
func S3KeyEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldS3Key, v))
}

// S3KeyNEQ applies the NEQ predicate on the "s3_key" field.
func S3KeyNEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldS3Key, v))
}

// S3KeyIn applies the In predicate on the "s3_key" field.
func S3KeyIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldS3Key, vs...))
}

// S3KeyNotIn applies the NotIn predicate on the "s3_key" field.
func S3KeyNotIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldS3Key, vs...))
}

// S3KeyGT applies the GT predicate on the "s3_key" field.
func S3KeyGT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGT(FieldS3Key, v))
}

// S3KeyGTE applies the GTE predicate on the "s3_key" field.
func S3KeyGTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGTE(FieldS3Key, v))
}

// S3KeyLT applies the LT predicate on the "s3_key" field.
func S3KeyLT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLT(FieldS3Key, v))
}

// S3KeyLTE applies the LTE predicate on the "s3_key" field.
func S3KeyLTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLTE(FieldS3Key, v))
}

// S3KeyContains applies the Contains predicate on the "s3_key" field.
func S3KeyContains(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContains(FieldS3Key, v))
}

// S3KeyHasPrefix applies the HasPrefix predicate on the "s3_key" field.
func S3KeyHasPrefix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasPrefix(FieldS3Key, v))
}

// S3KeyHasSuffix applies the HasSuffix predicate on the "s3_key" field.
func S3KeyHasSuffix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasSuffix(FieldS3Key, v))
}

// S3KeyEqualFold applies the EqualFold predicate on the "s3_key" field.
func S3KeyEqualFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEqualFold(FieldS3Key, v))
}

// S3KeyContainsFold applies the ContainsFold predicate on the "s3_key" field.
func S3KeyContainsFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContainsFold(FieldS3Key, v))
}

// ParsedMetaIsNil applies the IsNil predicate on the "parsed_meta" field.
func ParsedMetaIsNil() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIsNull(FieldParsedMeta))
}

// ParsedMetaNotNil applies the NotNil predicate on the "parsed_meta" field.
func ParsedMetaNotNil() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotNull(FieldParsedMeta))
}

// GuardStatusEQ applies the EQ predicate on the "guard_status" field.
func GuardStatusEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldGuardStatus, v))
}

// GuardStatusNEQ applies the NEQ predicate on the "guard_status" field.
func GuardStatusNEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldGuardStatus, v))
}

// GuardStatusIn applies the In predicate on the "guard_status" field.
func GuardStatusIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldGuardStatus, vs...))
}

// GuardStatusNotIn applies the NotIn predicate on the "guard_status" field.
func GuardStatusNotIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldGuardStatus, vs...))
}

// GuardStatusGT applies the GT predicate on the "guard_status" field.
func GuardStatusGT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGT(FieldGuardStatus, v))
}

// GuardStatusGTE applies the GTE predicate on the "guard_status" field.
func GuardStatusGTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGTE(FieldGuardStatus, v))
}

// GuardStatusLT applies the LT predicate on the "guard_status" field.
func GuardStatusLT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLT(FieldGuardStatus, v))
}

// GuardStatusLTE applies the LTE predicate on the "guard_status" field.
func GuardStatusLTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLTE(FieldGuardStatus, v))
}

// GuardStatusContains applies the Contains predicate on the "guard_status" field.
func GuardStatusContains(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContains(FieldGuardStatus, v))
}

// GuardStatusHasPrefix applies the HasPrefix predicate on the "guard_status" field.
func GuardStatusHasPrefix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasPrefix(FieldGuardStatus, v))
}

// GuardStatusHasSuffix applies the HasSuffix predicate on the "guard_status" field.
func GuardStatusHasSuffix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasSuffix(FieldGuardStatus, v))
}

// GuardStatusEqualFold applies the EqualFold predicate on the "guard_status" field.
func GuardStatusEqualFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEqualFold(FieldGuardStatus, v))
}

// GuardStatusContainsFold applies the ContainsFold predicate on the "guard_status" field.
func GuardStatusContainsFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContainsFold(FieldGuardStatus, v))
}

// GuardTaskIDEQ applies the EQ predicate on the "guard_task_id" field.
func GuardTaskIDEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldGuardTaskID, v))
}

// GuardTaskIDNEQ applies the NEQ predicate on the "guard_task_id" field.
func GuardTaskIDNEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldGuardTaskID, v))
}

// GuardTaskIDIn applies the In predicate on the "guard_task_id" field.
func GuardTaskIDIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldGuardTaskID, vs...))
}

// GuardTaskIDNotIn applies the NotIn predicate on the "guard_task_id" field.
func GuardTaskIDNotIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldGuardTaskID, vs...))
}

// GuardTaskIDGT applies the GT predicate on the "guard_task_id" field.
func GuardTaskIDGT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGT(FieldGuardTaskID, v))
}

// GuardTaskIDGTE applies the GTE predicate on the "guard_task_id" field.
func GuardTaskIDGTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGTE(FieldGuardTaskID, v))
}

// GuardTaskIDLT applies the LT predicate on the "guard_task_id" field.
func GuardTaskIDLT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLT(FieldGuardTaskID, v))
}

// GuardTaskIDLTE applies the LTE predicate on the "guard_task_id" field.
func GuardTaskIDLTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLTE(FieldGuardTaskID, v))
}

// GuardTaskIDContains applies the Contains predicate on the "guard_task_id" field.
func GuardTaskIDContains(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContains(FieldGuardTaskID, v))
}

// GuardTaskIDHasPrefix applies the HasPrefix predicate on the "guard_task_id" field.
func GuardTaskIDHasPrefix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasPrefix(FieldGuardTaskID, v))
}

// GuardTaskIDHasSuffix applies the HasSuffix predicate on the "guard_task_id" field.
func GuardTaskIDHasSuffix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasSuffix(FieldGuardTaskID, v))
}

// GuardTaskIDIsNil applies the IsNil predicate on the "guard_task_id" field.
func GuardTaskIDIsNil() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIsNull(FieldGuardTaskID))
}

// GuardTaskIDNotNil applies the NotNil predicate on the "guard_task_id" field.
func GuardTaskIDNotNil() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotNull(FieldGuardTaskID))
}

// GuardTaskIDEqualFold applies the EqualFold predicate on the "guard_task_id" field.
func GuardTaskIDEqualFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEqualFold(FieldGuardTaskID, v))
}

// GuardTaskIDContainsFold applies the ContainsFold predicate on the "guard_task_id" field.
func GuardTaskIDContainsFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContainsFold(FieldGuardTaskID, v))
}

// GuardDeadlineEQ applies the EQ predicate on the "guard_deadline" field.
func GuardDeadlineEQ(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldGuardDeadline, v))
}

// GuardDeadlineNEQ applies the NEQ predicate on the "guard_deadline" field.
func GuardDeadlineNEQ(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldGuardDeadline, v))
}

// GuardDeadlineIn applies the In predicate on the "guard_deadline" field.
func GuardDeadlineIn(vs ...time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldGuardDeadline, vs...))
}

// GuardDeadlineNotIn applies the NotIn predicate on the "guard_deadline" field.
func GuardDeadlineNotIn(vs ...time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldGuardDeadline, vs...))
}

// GuardDeadlineGT applies the GT predicate on the "guard_deadline" field.
func GuardDeadlineGT(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGT(FieldGuardDeadline, v))
}

// GuardDeadlineGTE applies the GTE predicate on the "guard_deadline" field.
func GuardDeadlineGTE(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGTE(FieldGuardDeadline, v))
}

// GuardDeadlineLT applies the LT predicate on the "guard_deadline" field.
func GuardDeadlineLT(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLT(FieldGuardDeadline, v))
}

// GuardDeadlineLTE applies the LTE predicate on the "guard_deadline" field.
func GuardDeadlineLTE(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLTE(FieldGuardDeadline, v))
}

// GuardDeadlineIsNil applies the IsNil predicate on the "guard_deadline" field.
func GuardDeadlineIsNil() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIsNull(FieldGuardDeadline))
}

// GuardDeadlineNotNil applies the NotNil predicate on the "guard_deadline" field.
func GuardDeadlineNotNil() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotNull(FieldGuardDeadline))
}

// GuardErrorEQ applies the EQ predicate on the "guard_error" field.
func GuardErrorEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldGuardError, v))
}

// GuardErrorNEQ applies the NEQ predicate on the "guard_error" field.
func GuardErrorNEQ(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldGuardError, v))
}

// GuardErrorIn applies the In predicate on the "guard_error" field.
func GuardErrorIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldGuardError, vs...))
}

// GuardErrorNotIn applies the NotIn predicate on the "guard_error" field.
func GuardErrorNotIn(vs ...string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldGuardError, vs...))
}

// GuardErrorGT applies the GT predicate on the "guard_error" field.
func GuardErrorGT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGT(FieldGuardError, v))
}

// GuardErrorGTE applies the GTE predicate on the "guard_error" field.
func GuardErrorGTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGTE(FieldGuardError, v))
}

// GuardErrorLT applies the LT predicate on the "guard_error" field.
func GuardErrorLT(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLT(FieldGuardError, v))
}

// GuardErrorLTE applies the LTE predicate on the "guard_error" field.
func GuardErrorLTE(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLTE(FieldGuardError, v))
}

// GuardErrorContains applies the Contains predicate on the "guard_error" field.
func GuardErrorContains(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContains(FieldGuardError, v))
}

// GuardErrorHasPrefix applies the HasPrefix predicate on the "guard_error" field.
func GuardErrorHasPrefix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasPrefix(FieldGuardError, v))
}

// GuardErrorHasSuffix applies the HasSuffix predicate on the "guard_error" field.
func GuardErrorHasSuffix(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldHasSuffix(FieldGuardError, v))
}

// GuardErrorIsNil applies the IsNil predicate on the "guard_error" field.
func GuardErrorIsNil() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIsNull(FieldGuardError))
}

// GuardErrorNotNil applies the NotNil predicate on the "guard_error" field.
func GuardErrorNotNil() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotNull(FieldGuardError))
}

// GuardErrorEqualFold applies the EqualFold predicate on the "guard_error" field.
func GuardErrorEqualFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEqualFold(FieldGuardError, v))
}

// GuardErrorContainsFold applies the ContainsFold predicate on the "guard_error" field.
func GuardErrorContainsFold(v string) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldContainsFold(FieldGuardError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSkill applies the HasEdge predicate on the "skill" edge.
func HasSkill() predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SkillTable, SkillColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSkillWith applies the HasEdge predicate on the "skill" edge with a given conditions (other predicates).
func HasSkillWith(preds ...predicate.AgentSkill) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(func(s *sql.Selector) {
		step := newSkillStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentSkillVersion) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentSkillVersion) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentSkillVersion) predicate.AgentSkillVersion {
	return predicate.AgentSkillVersion(sql.NotPredicates(p))
}
