// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const active = `-- name: Active :many
SELECT id, user_id, machine_id, device_name, alias, platform, os_version, arch, client_version, protocol_version, status, created_at, updated_at, last_seen_at, revoked_at FROM endpoints WHERE user_id = $1 AND status = 'active' ORDER BY machine_id
`

func (q *Queries) Active(ctx context.Context, userID string) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, active, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MachineID,
			&i.DeviceName,
			&i.Alias,
			&i.Platform,
			&i.OsVersion,
			&i.Arch,
			&i.ClientVersion,
			&i.ProtocolVersion,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const count = `-- name: Count :one
SELECT count(*) FROM endpoints WHERE user_id = $1
`

func (q *Queries) Count(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, count, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActive = `-- name: CountActive :one
SELECT count(*) FROM endpoints WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountActive(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActive, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const get = `-- name: Get :one
SELECT id, user_id, machine_id, device_name, alias, platform, os_version, arch, client_version, protocol_version, status, created_at, updated_at, last_seen_at, revoked_at FROM endpoints WHERE user_id = $1 AND machine_id = $2
`

type GetParams struct {
	UserID    string
	MachineID string
}

func (q *Queries) Get(ctx context.Context, arg GetParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, get, arg.UserID, arg.MachineID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MachineID,
		&i.DeviceName,
		&i.Alias,
		&i.Platform,
		&i.OsVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.ProtocolVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 AND status = 'active' AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	err := row.Scan(&id)
	return id, err
}

const page = `-- name: Page :many
SELECT id, user_id, machine_id, device_name, alias, platform, os_version, arch, client_version, protocol_version, status, created_at, updated_at, last_seen_at, revoked_at FROM endpoints WHERE user_id = $1 ORDER BY created_at DESC, id DESC
LIMIT $3::integer OFFSET $2::integer
`

type PageParams struct {
	UserID     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) Page(ctx context.Context, arg PageParams) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, page, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MachineID,
			&i.DeviceName,
			&i.Alias,
			&i.Platform,
			&i.OsVersion,
			&i.Arch,
			&i.ClientVersion,
			&i.ProtocolVersion,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const register = `-- name: Register :one
INSERT INTO endpoints (user_id, machine_id, device_name, platform, os_version, arch, client_version, protocol_version, last_seen_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,1,now())
ON CONFLICT (user_id, machine_id) DO UPDATE SET
    device_name = EXCLUDED.device_name, platform = EXCLUDED.platform,
    os_version = EXCLUDED.os_version, arch = EXCLUDED.arch, client_version = EXCLUDED.client_version,
    protocol_version = 1, last_seen_at = now(), updated_at = now()
WHERE endpoints.status = 'active'
RETURNING id, user_id, machine_id, device_name, alias, platform, os_version, arch, client_version, protocol_version, status, created_at, updated_at, last_seen_at, revoked_at
`

type RegisterParams struct {
	UserID        string
	MachineID     string
	DeviceName    string
	Platform      string
	OsVersion     string
	Arch          string
	ClientVersion string
}

func (q *Queries) Register(ctx context.Context, arg RegisterParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, register,
		arg.UserID,
		arg.MachineID,
		arg.DeviceName,
		arg.Platform,
		arg.OsVersion,
		arg.Arch,
		arg.ClientVersion,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MachineID,
		&i.DeviceName,
		&i.Alias,
		&i.Platform,
		&i.OsVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.ProtocolVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const rename = `-- name: Rename :one
UPDATE endpoints SET alias = $3::text, updated_at = now()
WHERE user_id = $1 AND machine_id = $2 RETURNING id, user_id, machine_id, device_name, alias, platform, os_version, arch, client_version, protocol_version, status, created_at, updated_at, last_seen_at, revoked_at
`

type RenameParams struct {
	UserID    string
	MachineID string
	Alias     *string
}

func (q *Queries) Rename(ctx context.Context, arg RenameParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, rename, arg.UserID, arg.MachineID, arg.Alias)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MachineID,
		&i.DeviceName,
		&i.Alias,
		&i.Platform,
		&i.OsVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.ProtocolVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const status = `-- name: Status :one
UPDATE endpoints SET status = $3::text,
    revoked_at = CASE WHEN $3::text = 'revoked' THEN now() ELSE NULL END,
    updated_at = now()
WHERE user_id = $1 AND machine_id = $2 RETURNING id, user_id, machine_id, device_name, alias, platform, os_version, arch, client_version, protocol_version, status, created_at, updated_at, last_seen_at, revoked_at
`

type StatusParams struct {
	UserID    string
	MachineID string
	Status    string
}

func (q *Queries) Status(ctx context.Context, arg StatusParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, status, arg.UserID, arg.MachineID, arg.Status)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MachineID,
		&i.DeviceName,
		&i.Alias,
		&i.Platform,
		&i.OsVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.ProtocolVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const touch = `-- name: Touch :exec
UPDATE endpoints SET last_seen_at = greatest(last_seen_at, $3::timestamptz)
WHERE user_id = $1 AND machine_id = $2
`

type TouchParams struct {
	UserID    string
	MachineID string
	SeenAt    time.Time
}

func (q *Queries) Touch(ctx context.Context, arg TouchParams) error {
	_, err := q.db.Exec(ctx, touch, arg.UserID, arg.MachineID, arg.SeenAt)
	return err
}
