// Code generated by ent, DO NOT EDIT.

package licenserecord

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the licenserecord type in the database.
	Label = "license_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLicenseID holds the string denoting the license_id field in the database.
	FieldLicenseID = "license_id"
	// FieldInstallationID holds the string denoting the installation_id field in the database.
	FieldInstallationID = "installation_id"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldCustomerName holds the string denoting the customer_name field in the database.
	FieldCustomerName = "customer_name"
	// FieldSeats holds the string denoting the seats field in the database.
	FieldSeats = "seats"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldPayloadJSON holds the string denoting the payload_json field in the database.
	FieldPayloadJSON = "payload_json"
	// FieldSignature holds the string denoting the signature field in the database.
	FieldSignature = "signature"
	// FieldKeyID holds the string denoting the key_id field in the database.
	FieldKeyID = "key_id"
	// FieldAlg holds the string denoting the alg field in the database.
	FieldAlg = "alg"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldImportedAt holds the string denoting the imported_at field in the database.
	FieldImportedAt = "imported_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the licenserecord in the database.
	Table = "license_records"
)

// Columns holds all SQL columns for licenserecord fields.
var Columns = []string{
	FieldID,
	FieldLicenseID,
	FieldInstallationID,
	FieldCustomerID,
	FieldCustomerName,
	FieldSeats,
	FieldIssuedAt,
	FieldExpiresAt,
	FieldPayloadJSON,
	FieldSignature,
	FieldKeyID,
	FieldAlg,
	FieldActive,
	FieldImportedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LicenseIDValidator is a validator for the "license_id" field. It is called by the builders before save.
	LicenseIDValidator func(string) error
	// InstallationIDValidator is a validator for the "installation_id" field. It is called by the builders before save.
	InstallationIDValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Alg defines the type for the "alg" enum field.
type Alg string

// Alg values.
const (
	AlgEd25519 Alg = "Ed25519"
)

func (a Alg) String() string {
	return string(a)
}

// AlgValidator is a validator for the "alg" field enum values. It is called by the builders before save.
func AlgValidator(a Alg) error {
	switch a {
	case AlgEd25519:
		return nil
	default:
		return fmt.Errorf("licenserecord: invalid enum value for alg field: %q", a)
	}
}

// OrderOption defines the ordering options for the LicenseRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLicenseID orders the results by the license_id field.
func ByLicenseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseID, opts...).ToFunc()
}

// ByInstallationID orders the results by the installation_id field.
func ByInstallationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallationID, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// ByCustomerName orders the results by the customer_name field.
func ByCustomerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerName, opts...).ToFunc()
}

// BySeats orders the results by the seats field.
func BySeats(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeats, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByPayloadJSON orders the results by the payload_json field.
func ByPayloadJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadJSON, opts...).ToFunc()
}

// BySignature orders the results by the signature field.
func BySignature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignature, opts...).ToFunc()
}

// ByKeyID orders the results by the key_id field.
func ByKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyID, opts...).ToFunc()
}

// ByAlg orders the results by the alg field.
func ByAlg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlg, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByImportedAt orders the results by the imported_at field.
func ByImportedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
