// Code generated by ent, DO NOT EDIT.

package licenserecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldID, id))
}

// LicenseID applies equality check predicate on the "license_id" field. It's identical to LicenseIDEQ.
func LicenseID(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldLicenseID, v))
}

// InstallationID applies equality check predicate on the "installation_id" field. It's identical to InstallationIDEQ.
func InstallationID(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldInstallationID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerName applies equality check predicate on the "customer_name" field. It's identical to CustomerNameEQ.
func CustomerName(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldCustomerName, v))
}

// Seats applies equality check predicate on the "seats" field. It's identical to SeatsEQ.
func Seats(v int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldSeats, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldIssuedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldExpiresAt, v))
}

// PayloadJSON applies equality check predicate on the "payload_json" field. It's identical to PayloadJSONEQ.
func PayloadJSON(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldPayloadJSON, v))
}

// Signature applies equality check predicate on the "signature" field. It's identical to SignatureEQ.
func Signature(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldSignature, v))
}

// KeyID applies equality check predicate on the "key_id" field. It's identical to KeyIDEQ.
func KeyID(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldKeyID, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldActive, v))
}

// ImportedAt applies equality check predicate on the "imported_at" field. It's identical to ImportedAtEQ.
func ImportedAt(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldImportedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// LicenseIDEQ applies the EQ predicate on the "license_id" field.
func LicenseIDEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldLicenseID, v))
}

// LicenseIDNEQ applies the NEQ predicate on the "license_id" field.
func LicenseIDNEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldLicenseID, v))
}

// LicenseIDIn applies the In predicate on the "license_id" field.
func LicenseIDIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldLicenseID, vs...))
}

// LicenseIDNotIn applies the NotIn predicate on the "license_id" field.
func LicenseIDNotIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldLicenseID, vs...))
}

// LicenseIDGT applies the GT predicate on the "license_id" field.
func LicenseIDGT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldLicenseID, v))
}

// LicenseIDGTE applies the GTE predicate on the "license_id" field.
func LicenseIDGTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldLicenseID, v))
}

// LicenseIDLT applies the LT predicate on the "license_id" field.
func LicenseIDLT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldLicenseID, v))
}

// LicenseIDLTE applies the LTE predicate on the "license_id" field.
func LicenseIDLTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldLicenseID, v))
}

// LicenseIDContains applies the Contains predicate on the "license_id" field.
func LicenseIDContains(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContains(FieldLicenseID, v))
}

// LicenseIDHasPrefix applies the HasPrefix predicate on the "license_id" field.
func LicenseIDHasPrefix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasPrefix(FieldLicenseID, v))
}

// LicenseIDHasSuffix applies the HasSuffix predicate on the "license_id" field.
func LicenseIDHasSuffix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasSuffix(FieldLicenseID, v))
}

// LicenseIDEqualFold applies the EqualFold predicate on the "license_id" field.
func LicenseIDEqualFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEqualFold(FieldLicenseID, v))
}

// LicenseIDContainsFold applies the ContainsFold predicate on the "license_id" field.
func LicenseIDContainsFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContainsFold(FieldLicenseID, v))
}

// InstallationIDEQ applies the EQ predicate on the "installation_id" field.
func InstallationIDEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldInstallationID, v))
}

// InstallationIDNEQ applies the NEQ predicate on the "installation_id" field.
func InstallationIDNEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldInstallationID, v))
}

// InstallationIDIn applies the In predicate on the "installation_id" field.
func InstallationIDIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldInstallationID, vs...))
}

// InstallationIDNotIn applies the NotIn predicate on the "installation_id" field.
func InstallationIDNotIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldInstallationID, vs...))
}

// InstallationIDGT applies the GT predicate on the "installation_id" field.
func InstallationIDGT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldInstallationID, v))
}

// InstallationIDGTE applies the GTE predicate on the "installation_id" field.
func InstallationIDGTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldInstallationID, v))
}

// InstallationIDLT applies the LT predicate on the "installation_id" field.
func InstallationIDLT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldInstallationID, v))
}

// InstallationIDLTE applies the LTE predicate on the "installation_id" field.
func InstallationIDLTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldInstallationID, v))
}

// InstallationIDContains applies the Contains predicate on the "installation_id" field.
func InstallationIDContains(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContains(FieldInstallationID, v))
}

// InstallationIDHasPrefix applies the HasPrefix predicate on the "installation_id" field.
func InstallationIDHasPrefix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasPrefix(FieldInstallationID, v))
}

// InstallationIDHasSuffix applies the HasSuffix predicate on the "installation_id" field.
func InstallationIDHasSuffix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasSuffix(FieldInstallationID, v))
}

// InstallationIDEqualFold applies the EqualFold predicate on the "installation_id" field.
func InstallationIDEqualFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEqualFold(FieldInstallationID, v))
}

// InstallationIDContainsFold applies the ContainsFold predicate on the "installation_id" field.
func InstallationIDContainsFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContainsFold(FieldInstallationID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDIsNil applies the IsNil predicate on the "customer_id" field.
func CustomerIDIsNil() predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIsNull(FieldCustomerID))
}

// CustomerIDNotNil applies the NotNil predicate on the "customer_id" field.
func CustomerIDNotNil() predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotNull(FieldCustomerID))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContainsFold(FieldCustomerID, v))
}

// CustomerNameEQ applies the EQ predicate on the "customer_name" field.
func CustomerNameEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldCustomerName, v))
}

// CustomerNameNEQ applies the NEQ predicate on the "customer_name" field.
func CustomerNameNEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldCustomerName, v))
}

// CustomerNameIn applies the In predicate on the "customer_name" field.
func CustomerNameIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldCustomerName, vs...))
}

// CustomerNameNotIn applies the NotIn predicate on the "customer_name" field.
func CustomerNameNotIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldCustomerName, vs...))
}

// CustomerNameGT applies the GT predicate on the "customer_name" field.
func CustomerNameGT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldCustomerName, v))
}

// CustomerNameGTE applies the GTE predicate on the "customer_name" field.
func CustomerNameGTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldCustomerName, v))
}

// CustomerNameLT applies the LT predicate on the "customer_name" field.
func CustomerNameLT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldCustomerName, v))
}

// CustomerNameLTE applies the LTE predicate on the "customer_name" field.
func CustomerNameLTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldCustomerName, v))
}

// CustomerNameContains applies the Contains predicate on the "customer_name" field.
func CustomerNameContains(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContains(FieldCustomerName, v))
}

// CustomerNameHasPrefix applies the HasPrefix predicate on the "customer_name" field.
func CustomerNameHasPrefix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasPrefix(FieldCustomerName, v))
}

// CustomerNameHasSuffix applies the HasSuffix predicate on the "customer_name" field.
func CustomerNameHasSuffix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasSuffix(FieldCustomerName, v))
}

// CustomerNameIsNil applies the IsNil predicate on the "customer_name" field.
func CustomerNameIsNil() predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIsNull(FieldCustomerName))
}

// CustomerNameNotNil applies the NotNil predicate on the "customer_name" field.
func CustomerNameNotNil() predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotNull(FieldCustomerName))
}

// CustomerNameEqualFold applies the EqualFold predicate on the "customer_name" field.
func CustomerNameEqualFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEqualFold(FieldCustomerName, v))
}

// CustomerNameContainsFold applies the ContainsFold predicate on the "customer_name" field.
func CustomerNameContainsFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContainsFold(FieldCustomerName, v))
}

// SeatsEQ applies the EQ predicate on the "seats" field.
func SeatsEQ(v int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldSeats, v))
}

// SeatsNEQ applies the NEQ predicate on the "seats" field.
func SeatsNEQ(v int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldSeats, v))
}

// SeatsIn applies the In predicate on the "seats" field.
func SeatsIn(vs ...int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldSeats, vs...))
}

// SeatsNotIn applies the NotIn predicate on the "seats" field.
func SeatsNotIn(vs ...int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldSeats, vs...))
}

// SeatsGT applies the GT predicate on the "seats" field.
func SeatsGT(v int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldSeats, v))
}

// SeatsGTE applies the GTE predicate on the "seats" field.
func SeatsGTE(v int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldSeats, v))
}

// SeatsLT applies the LT predicate on the "seats" field.
func SeatsLT(v int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldSeats, v))
}

// SeatsLTE applies the LTE predicate on the "seats" field.
func SeatsLTE(v int) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldSeats, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldIssuedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldExpiresAt, v))
}

// PayloadJSONEQ applies the EQ predicate on the "payload_json" field.
func PayloadJSONEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldPayloadJSON, v))
}

// PayloadJSONNEQ applies the NEQ predicate on the "payload_json" field.
func PayloadJSONNEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldPayloadJSON, v))
}

// PayloadJSONIn applies the In predicate on the "payload_json" field.
func PayloadJSONIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldPayloadJSON, vs...))
}

// PayloadJSONNotIn applies the NotIn predicate on the "payload_json" field.
func PayloadJSONNotIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldPayloadJSON, vs...))
}

// PayloadJSONGT applies the GT predicate on the "payload_json" field.
func PayloadJSONGT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldPayloadJSON, v))
}

// PayloadJSONGTE applies the GTE predicate on the "payload_json" field.
func PayloadJSONGTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldPayloadJSON, v))
}

// PayloadJSONLT applies the LT predicate on the "payload_json" field.
func PayloadJSONLT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldPayloadJSON, v))
}

// PayloadJSONLTE applies the LTE predicate on the "payload_json" field.
func PayloadJSONLTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldPayloadJSON, v))
}

// PayloadJSONContains applies the Contains predicate on the "payload_json" field.
func PayloadJSONContains(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContains(FieldPayloadJSON, v))
}

// PayloadJSONHasPrefix applies the HasPrefix predicate on the "payload_json" field.
func PayloadJSONHasPrefix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasPrefix(FieldPayloadJSON, v))
}

// PayloadJSONHasSuffix applies the HasSuffix predicate on the "payload_json" field.
func PayloadJSONHasSuffix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasSuffix(FieldPayloadJSON, v))
}

// PayloadJSONEqualFold applies the EqualFold predicate on the "payload_json" field.
func PayloadJSONEqualFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEqualFold(FieldPayloadJSON, v))
}

// PayloadJSONContainsFold applies the ContainsFold predicate on the "payload_json" field.
func PayloadJSONContainsFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContainsFold(FieldPayloadJSON, v))
}

// SignatureEQ applies the EQ predicate on the "signature" field.
func SignatureEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldSignature, v))
}

// SignatureNEQ applies the NEQ predicate on the "signature" field.
func SignatureNEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldSignature, v))
}

// SignatureIn applies the In predicate on the "signature" field.
func SignatureIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldSignature, vs...))
}

// SignatureNotIn applies the NotIn predicate on the "signature" field.
func SignatureNotIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldSignature, vs...))
}

// SignatureGT applies the GT predicate on the "signature" field.
func SignatureGT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldSignature, v))
}

// SignatureGTE applies the GTE predicate on the "signature" field.
func SignatureGTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldSignature, v))
}

// SignatureLT applies the LT predicate on the "signature" field.
func SignatureLT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldSignature, v))
}

// SignatureLTE applies the LTE predicate on the "signature" field.
func SignatureLTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldSignature, v))
}

// SignatureContains applies the Contains predicate on the "signature" field.
func SignatureContains(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContains(FieldSignature, v))
}

// SignatureHasPrefix applies the HasPrefix predicate on the "signature" field.
func SignatureHasPrefix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasPrefix(FieldSignature, v))
}

// SignatureHasSuffix applies the HasSuffix predicate on the "signature" field.
func SignatureHasSuffix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasSuffix(FieldSignature, v))
}

// SignatureEqualFold applies the EqualFold predicate on the "signature" field.
func SignatureEqualFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEqualFold(FieldSignature, v))
}

// SignatureContainsFold applies the ContainsFold predicate on the "signature" field.
func SignatureContainsFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContainsFold(FieldSignature, v))
}

// KeyIDEQ applies the EQ predicate on the "key_id" field.
func KeyIDEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldKeyID, v))
}

// KeyIDNEQ applies the NEQ predicate on the "key_id" field.
func KeyIDNEQ(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldKeyID, v))
}

// KeyIDIn applies the In predicate on the "key_id" field.
func KeyIDIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldKeyID, vs...))
}

// KeyIDNotIn applies the NotIn predicate on the "key_id" field.
func KeyIDNotIn(vs ...string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldKeyID, vs...))
}

// KeyIDGT applies the GT predicate on the "key_id" field.
func KeyIDGT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldKeyID, v))
}

// KeyIDGTE applies the GTE predicate on the "key_id" field.
func KeyIDGTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldKeyID, v))
}

// KeyIDLT applies the LT predicate on the "key_id" field.
func KeyIDLT(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldKeyID, v))
}

// KeyIDLTE applies the LTE predicate on the "key_id" field.
func KeyIDLTE(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldKeyID, v))
}

// KeyIDContains applies the Contains predicate on the "key_id" field.
func KeyIDContains(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContains(FieldKeyID, v))
}

// KeyIDHasPrefix applies the HasPrefix predicate on the "key_id" field.
func KeyIDHasPrefix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasPrefix(FieldKeyID, v))
}

// KeyIDHasSuffix applies the HasSuffix predicate on the "key_id" field.
func KeyIDHasSuffix(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldHasSuffix(FieldKeyID, v))
}

// KeyIDEqualFold applies the EqualFold predicate on the "key_id" field.
func KeyIDEqualFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEqualFold(FieldKeyID, v))
}

// KeyIDContainsFold applies the ContainsFold predicate on the "key_id" field.
func KeyIDContainsFold(v string) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldContainsFold(FieldKeyID, v))
}

// AlgEQ applies the EQ predicate on the "alg" field.
func AlgEQ(v Alg) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldAlg, v))
}

// AlgNEQ applies the NEQ predicate on the "alg" field.
func AlgNEQ(v Alg) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldAlg, v))
}

// AlgIn applies the In predicate on the "alg" field.
func AlgIn(vs ...Alg) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldAlg, vs...))
}

// AlgNotIn applies the NotIn predicate on the "alg" field.
func AlgNotIn(vs ...Alg) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldAlg, vs...))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldActive, v))
}

// ImportedAtEQ applies the EQ predicate on the "imported_at" field.
func ImportedAtEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldImportedAt, v))
}

// ImportedAtNEQ applies the NEQ predicate on the "imported_at" field.
func ImportedAtNEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldImportedAt, v))
}

// ImportedAtIn applies the In predicate on the "imported_at" field.
func ImportedAtIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldImportedAt, vs...))
}

// ImportedAtNotIn applies the NotIn predicate on the "imported_at" field.
func ImportedAtNotIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldImportedAt, vs...))
}

// ImportedAtGT applies the GT predicate on the "imported_at" field.
func ImportedAtGT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldImportedAt, v))
}

// ImportedAtGTE applies the GTE predicate on the "imported_at" field.
func ImportedAtGTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldImportedAt, v))
}

// ImportedAtLT applies the LT predicate on the "imported_at" field.
func ImportedAtLT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldImportedAt, v))
}

// ImportedAtLTE applies the LTE predicate on the "imported_at" field.
func ImportedAtLTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldImportedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LicenseRecord) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LicenseRecord) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LicenseRecord) predicate.LicenseRecord {
	return predicate.LicenseRecord(sql.NotPredicates(p))
}
