// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// TeamGroup is the predicate function for teamgroup builders.
type TeamGroup func(*sql.Selector)

// TeamGroupMember is the predicate function for teamgroupmember builders.
type TeamGroupMember func(*sql.Selector)

// TeamMember is the predicate function for teammember builders.
type TeamMember func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserIdentity is the predicate function for useridentity builders.
type UserIdentity func(*sql.Selector)
